/**
 * bar_trans_patch.js
 * ---------------------------------------------------------------
 * Extends BAR_TRANS with all 30 extra languages.
 * Includes: single Caffè D'Orzo / Ginseng (no Piccolo/Grande),
 * single Succo di Frutta (flavor picked via popup), Ricard, Whiskey.
 * Paste this AFTER the existing BAR_TRANS / BAR_ITEMS block.
 * ---------------------------------------------------------------
 */
(function () {
  var PATCH = {
    'nl': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Cafeïnevrije Koffie',
      "Caffè d'Orzo": 'Gerstenkoffie',
      'Caffè Ginseng': 'Ginsengkoffie',
      'Caffè Corretto': 'Koffie met Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Warme Thee',
      'Infusi': 'Kruidenthee',
      'Cioccolata Calda': 'Warme Chocolade',
      'Acqua Naturale 1 L': 'Plat Water 1 L',
      'Acqua Gassata 1 L': 'Bruisend Water 1 L',
      'Estathé Limone': 'Ijsthee Citroen',
      'Estathé Pesca': 'Ijsthee Perzik',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citroen',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Vruchtensap',
      'Birra Bottiglia 33 cl': 'Fles Bier 33 cl',
      'Birra Analcolica': 'Alcoholvrij Bier',
      'Digestivi': 'Digestieven',
      'Shot Alcolici': 'Alcoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citroen'
    },
    'es': {
      'Caffè Espresso': 'Café Espresso',
      'Caffè Decaffeinato': 'Café Descafeinado',
      "Caffè d'Orzo": 'Café de Cebada',
      'Caffè Ginseng': 'Café de Ginseng',
      'Caffè Corretto': 'Café con Grappa',
      'Caffè Latte': 'Café con Leche',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Té Caliente',
      'Infusi': 'Infusiones',
      'Cioccolata Calda': 'Chocolate Caliente',
      'Acqua Naturale 1 L': 'Agua Sin Gas 1 L',
      'Acqua Gassata 1 L': 'Agua Con Gas 1 L',
      'Estathé Limone': 'Té Frío Limón',
      'Estathé Pesca': 'Té Frío Melocotón',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limón',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Zumo de Frutas',
      'Birra Bottiglia 33 cl': 'Cerveza Botella 33 cl',
      'Birra Analcolica': 'Cerveza Sin Alcohol',
      'Digestivi': 'Digestivos',
      'Distillati': 'Destilados',
      'Shot Alcolici': 'Chupitos',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Ron & Cola',
      'Gin Tonic': 'Gin Tónic',
      'Gin Lemon': 'Gin Limón'
    },
    'pt': {
      'Caffè Espresso': 'Café Expresso',
      'Caffè Decaffeinato': 'Café Descafeinado',
      "Caffè d'Orzo": 'Café de Cevada',
      'Caffè Ginseng': 'Café de Ginseng',
      'Caffè Corretto': 'Café com Grappa',
      'Caffè Latte': 'Café com Leite',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Chá Quente',
      'Infusi': 'Infusões',
      'Cioccolata Calda': 'Chocolate Quente',
      'Acqua Naturale 1 L': 'Água Sem Gás 1 L',
      'Acqua Gassata 1 L': 'Água Com Gás 1 L',
      'Estathé Limone': 'Chá Frio Limão',
      'Estathé Pesca': 'Chá Frio Pêssego',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limão',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Sumo de Fruta',
      'Birra Bottiglia 33 cl': 'Cerveja Garrafa 33 cl',
      'Birra Analcolica': 'Cerveja Sem Álcool',
      'Digestivi': 'Digestivos',
      'Shot Alcolici': 'Shots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tónico',
      'Gin Lemon': 'Gin Limão'
    },
    'ru': {
      'Caffè Espresso': 'Кофе Эспрессо',
      'Caffè Decaffeinato': 'Кофе без Кофеина',
      "Caffè d'Orzo": 'Ячменный Кофе',
      'Caffè Ginseng': 'Женьшеневый Кофе',
      'Caffè Corretto': 'Кофе с Граппой',
      'Caffè Latte': 'Кофе Латте',
      'Latte Macchiato': 'Латте Макиато',
      'Tè Caldo': 'Горячий Чай',
      'Infusi': 'Травяной Чай',
      'Cioccolata Calda': 'Горячий Шоколад',
      'Acqua Naturale 1 L': 'Негазированная Вода 1 л',
      'Acqua Gassata 1 L': 'Газированная Вода 1 л',
      'Estathé Limone': 'Холодный Чай Лимон',
      'Estathé Pesca': 'Холодный Чай Персик',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Фруктовый Сок',
      'Birra Bottiglia 33 cl': 'Пиво в Бутылке 33 кл',
      'Birra Analcolica': 'Безалкогольное Пиво',
      'Digestivi': 'Дижестивы',
      'Shot Alcolici': 'Алкогольные Шоты',
      'Ricard': 'Рикар',
      'Whiskey': 'Виски',
      'Whisky & Coca': 'Виски & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин & Тоник',
      'Gin Lemon': 'Джин & Лимон'
    },
    'pl': {
      'Caffè Espresso': 'Kawa Espresso',
      'Caffè Decaffeinato': 'Kawa Bezkofeinowa',
      "Caffè d'Orzo": 'Kawa Jęczmienna',
      'Caffè Ginseng': 'Kawa Żeńszeniowa',
      'Caffè Corretto': 'Kawa z Grappą',
      'Caffè Latte': 'Kawa Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Gorąca Herbata',
      'Infusi': 'Herbaty Ziołowe',
      'Cioccolata Calda': 'Gorąca Czekolada',
      'Acqua Naturale 1 L': 'Woda Niegazowana 1 L',
      'Acqua Gassata 1 L': 'Woda Gazowana 1 L',
      'Estathé Limone': 'Mrożona Herbata Cytrynowa',
      'Estathé Pesca': 'Mrożona Herbata Brzoskwiniowa',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Cytryna',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Sok Owocowy',
      'Birra Bottiglia 33 cl': 'Piwo Butelkowe 33 cl',
      'Birra Analcolica': 'Piwo Bezalkoholowe',
      'Digestivi': 'Digestify',
      'Shot Alcolici': 'Shoty Alkoholowe',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Cytryna'
    },
    'uk': {
      'Caffè Espresso': 'Кава Еспресо',
      'Caffè Decaffeinato': 'Кава без Кофеїну',
      "Caffè d'Orzo": 'Ячмінна Кава',
      'Caffè Ginseng': 'Женьшенева Кава',
      'Caffè Corretto': 'Кава з Граппою',
      'Caffè Latte': 'Кава Латте',
      'Latte Macchiato': 'Латте Макіато',
      'Tè Caldo': 'Гарячий Чай',
      'Infusi': "Трав'яний Чай",
      'Cioccolata Calda': 'Гарячий Шоколад',
      'Acqua Naturale 1 L': 'Негазована Вода 1 л',
      'Acqua Gassata 1 L': 'Газована Вода 1 л',
      'Estathé Limone': 'Холодний Чай Лимон',
      'Estathé Pesca': 'Холодний Чай Персик',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Фруктовий Сік',
      'Birra Bottiglia 33 cl': 'Пиво в Пляшці 33 кл',
      'Birra Analcolica': 'Безалкогольне Пиво',
      'Digestivi': 'Дижестиви',
      'Shot Alcolici': 'Алкогольні Шоти',
      'Ricard': 'Рікар',
      'Whiskey': 'Віскі',
      'Whisky & Coca': 'Віскі & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин & Тонік',
      'Gin Lemon': 'Джин & Лимон'
    },
    'ro': {
      'Caffè Espresso': 'Cafea Espresso',
      'Caffè Decaffeinato': 'Cafea Decofeinizată',
      "Caffè d'Orzo": 'Cafea de Orz',
      'Caffè Ginseng': 'Cafea de Ginseng',
      'Caffè Corretto': 'Cafea cu Grappa',
      'Caffè Latte': 'Cafea Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Ceai Cald',
      'Infusi': 'Infuzii',
      'Cioccolata Calda': 'Ciocolată Caldă',
      'Acqua Naturale 1 L': 'Apă Plată 1 L',
      'Acqua Gassata 1 L': 'Apă Carbogazoasă 1 L',
      'Estathé Limone': 'Ceai Rece Lămâie',
      'Estathé Pesca': 'Ceai Rece Piersică',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Lămâie',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Suc de Fructe',
      'Birra Bottiglia 33 cl': 'Bere Sticlă 33 cl',
      'Birra Analcolica': 'Bere Fără Alcool',
      'Digestivi': 'Digestive',
      'Shot Alcolici': 'Shoturi Alcoolice',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin Tonic',
      'Gin Lemon': 'Gin Lămâie'
    },
    'sv': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfritt Kaffe',
      "Caffè d'Orzo": 'Kornkaffe',
      'Caffè Ginseng': 'Ginsengkaffe',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Varmt Te',
      'Infusi': 'Örtte',
      'Cioccolata Calda': 'Varm Choklad',
      'Acqua Naturale 1 L': 'Stilla Vatten 1 L',
      'Acqua Gassata 1 L': 'Kolsyrat Vatten 1 L',
      'Estathé Limone': 'Iste Citron',
      'Estathé Pesca': 'Iste Persika',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Fruktjuice',
      'Birra Bottiglia 33 cl': 'Flasköl 33 cl',
      'Birra Analcolica': 'Alkoholfri Öl',
      'Digestivi': 'Digestif',
      'Shot Alcolici': 'Alkoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citron'
    },
    'da': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfri Kaffe',
      "Caffè d'Orzo": 'Bygkaffe',
      'Caffè Ginseng': 'Ginsengkaffe',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Varm Te',
      'Infusi': 'Urtethe',
      'Cioccolata Calda': 'Varm Chokolade',
      'Acqua Naturale 1 L': 'Stille Vand 1 L',
      'Acqua Gassata 1 L': 'Kulsyreholdigt Vand 1 L',
      'Estathé Limone': 'Isite Citron',
      'Estathé Pesca': 'Isite Fersken',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Frugtjuice',
      'Birra Bottiglia 33 cl': 'Ølflasker 33 cl',
      'Birra Analcolica': 'Alkoholfri Øl',
      'Digestivi': 'Digestif',
      'Shot Alcolici': 'Alkoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Citron'
    },
    'no': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Koffeinfri Kaffe',
      "Caffè d'Orzo": 'Byggkaffe',
      'Caffè Ginseng': 'Ginsengkaffe',
      'Caffè Corretto': 'Kaffe med Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Varm Te',
      'Infusi': 'Urtete',
      'Cioccolata Calda': 'Varm Sjokolade',
      'Acqua Naturale 1 L': 'Stille Vann 1 L',
      'Acqua Gassata 1 L': 'Kullsyreholdig Vann 1 L',
      'Estathé Limone': 'Iste Sitron',
      'Estathé Pesca': 'Iste Fersken',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Sitron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Fruktjuice',
      'Birra Bottiglia 33 cl': 'Ølflasker 33 cl',
      'Birra Analcolica': 'Alkoholfri Øl',
      'Digestivi': 'Digestif',
      'Shot Alcolici': 'Alkoholshots',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rom & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Sitron'
    },
    'fi': {
      'Caffè Espresso': 'Espresso',
      'Caffè Decaffeinato': 'Kofeiiniton Kahvi',
      "Caffè d'Orzo": 'Ohrakahvi',
      'Caffè Ginseng': 'Ginsengkahvi',
      'Caffè Corretto': 'Kahvi Grappalla',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Kuuma Tee',
      'Infusi': 'Yrttitee',
      'Cioccolata Calda': 'Kuuma Kaakao',
      'Acqua Naturale 1 L': 'Hanavesi 1 L',
      'Acqua Gassata 1 L': 'Kivennäisvesi 1 L',
      'Estathé Limone': 'Jäätee Sitruuna',
      'Estathé Pesca': 'Jäätee Persikka',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Sitruuna',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Hedelmämehu',
      'Birra Bottiglia 33 cl': 'Olutpullo 33 cl',
      'Birra Analcolica': 'Alkoholiton Olut',
      'Digestivi': 'Digestiivit',
      'Shot Alcolici': 'Alkoholishotteja',
      'Ricard': 'Ricard',
      'Whiskey': 'Viski',
      'Whisky & Coca': 'Viski & Cola',
      'Rhum & Coca': 'Rommi & Cola',
      'Gin Tonic': 'Gin & Tonic',
      'Gin Lemon': 'Gin & Sitruuna'
    },
    'el': {
      'Caffè Espresso': 'Καφές Εσπρέσο',
      'Caffè Decaffeinato': 'Καφές Ντεκαφεϊνέ',
      "Caffè d'Orzo": 'Καφές Κριθαριού',
      'Caffè Ginseng': 'Καφές Τζίνσενγκ',
      'Caffè Corretto': 'Καφές με Γκράπα',
      'Caffè Latte': 'Καφές Λάτε',
      'Latte Macchiato': 'Λάτε Μακιάτο',
      'Tè Caldo': 'Ζεστό Τσάι',
      'Infusi': 'Αφεψήματα',
      'Cioccolata Calda': 'Ζεστή Σοκολάτα',
      'Acqua Naturale 1 L': 'Φυσικό Νερό 1 L',
      'Acqua Gassata 1 L': 'Ανθρακούχο Νερό 1 L',
      'Estathé Limone': 'Παγωμένο Τσάι Λεμόνι',
      'Estathé Pesca': 'Παγωμένο Τσάι Ροδάκινο',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Λεμόνι',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Χυμός Φρούτων',
      'Birra Bottiglia 33 cl': 'Μπύρα Μπουκάλι 33 cl',
      'Birra Analcolica': 'Μπύρα Χωρίς Αλκοόλ',
      'Digestivi': 'Πεπτικά',
      'Shot Alcolici': 'Σφηνάκια',
      'Ricard': 'Ρικάρ',
      'Whiskey': 'Ουίσκι',
      'Whisky & Coca': 'Ουίσκι & Κόλα',
      'Rhum & Coca': 'Ρούμι & Κόλα',
      'Gin Tonic': 'Τζιν Τόνικ',
      'Gin Lemon': 'Τζιν Λεμόνι'
    },
    'cs': {
      'Caffè Espresso': 'Káva Espresso',
      'Caffè Decaffeinato': 'Bezkofeinová Káva',
      "Caffè d'Orzo": 'Ječmenná Káva',
      'Caffè Ginseng': 'Ženšenová Káva',
      'Caffè Corretto': 'Káva s Grappou',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Horký Čaj',
      'Infusi': 'Bylinné Čaje',
      'Cioccolata Calda': 'Horká Čokoláda',
      'Acqua Naturale 1 L': 'Neperlivá Voda 1 L',
      'Acqua Gassata 1 L': 'Perlivá Voda 1 L',
      'Estathé Limone': 'Ledový Čaj Citron',
      'Estathé Pesca': 'Ledový Čaj Broskev',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citron',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Ovocný Džus',
      'Birra Bottiglia 33 cl': 'Pivo v Láhvi 33 cl',
      'Birra Analcolica': 'Nealkoholické Pivo',
      'Digestivi': 'Digestivy',
      'Shot Alcolici': 'Alkoholové Shoty',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citron'
    },
    'hu': {
      'Caffè Espresso': 'Eszpresszó',
      'Caffè Decaffeinato': 'Koffeinmentes Kávé',
      "Caffè d'Orzo": 'Árpakávé',
      'Caffè Ginseng': 'Ginszeng Kávé',
      'Caffè Corretto': 'Kávé Grappával',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Meleg Tea',
      'Infusi': 'Gyógynövény Tea',
      'Cioccolata Calda': 'Forró Csokoládé',
      'Acqua Naturale 1 L': 'Szénsavmentes Víz 1 L',
      'Acqua Gassata 1 L': 'Szénsavas Víz 1 L',
      'Estathé Limone': 'Jeges Tea Citrom',
      'Estathé Pesca': 'Jeges Tea Barack',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citrom',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Gyümölcslé',
      'Birra Bottiglia 33 cl': 'Üveges Sör 33 cl',
      'Birra Analcolica': 'Alkoholmentes Sör',
      'Digestivi': 'Digestifek',
      'Shot Alcolici': 'Alkoholos Shotok',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citrom'
    },
    'bg': {
      'Caffè Espresso': 'Кафе Еспресо',
      'Caffè Decaffeinato': 'Безкофеиново Кафе',
      "Caffè d'Orzo": 'Ечемично Кафе',
      'Caffè Ginseng': 'Женшеново Кафе',
      'Caffè Corretto': 'Кафе с Грапа',
      'Caffè Latte': 'Кафе Лате',
      'Latte Macchiato': 'Лате Макиато',
      'Tè Caldo': 'Горещ Чай',
      'Infusi': 'Билков Чай',
      'Cioccolata Calda': 'Горещ Шоколад',
      'Acqua Naturale 1 L': 'Негазирана Вода 1 л',
      'Acqua Gassata 1 L': 'Газирана Вода 1 л',
      'Estathé Limone': 'Студен Чай Лимон',
      'Estathé Pesca': 'Студен Чай Праскова',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Лимон',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Плодов Сок',
      'Birra Bottiglia 33 cl': 'Бутилирана Бира 33 кл',
      'Birra Analcolica': 'Безалкохолна Бира',
      'Digestivi': 'Дижестиви',
      'Shot Alcolici': 'Алкохолни Шотове',
      'Ricard': 'Рикар',
      'Whiskey': 'Уиски',
      'Whisky & Coca': 'Уиски & Кола',
      'Rhum & Coca': 'Ром & Кола',
      'Gin Tonic': 'Джин Тоник',
      'Gin Lemon': 'Джин Лимон'
    },
    'sk': {
      'Caffè Espresso': 'Káva Espresso',
      'Caffè Decaffeinato': 'Bezkofeinová Káva',
      "Caffè d'Orzo": 'Jačmenná Káva',
      'Caffè Ginseng': 'Ženšenová Káva',
      'Caffè Corretto': 'Káva s Grappou',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Horúci Čaj',
      'Infusi': 'Bylinkové Čaje',
      'Cioccolata Calda': 'Horúca Čokoláda',
      'Acqua Naturale 1 L': 'Neperlivá Voda 1 L',
      'Acqua Gassata 1 L': 'Perlivá Voda 1 L',
      'Estathé Limone': 'Ľadový Čaj Citrón',
      'Estathé Pesca': 'Ľadový Čaj Broskyňa',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Citrón',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Ovocný Džús',
      'Birra Bottiglia 33 cl': 'Fľaška Piva 33 cl',
      'Birra Analcolica': 'Nealkoholické Pivo',
      'Digestivi': 'Digestívy',
      'Shot Alcolici': 'Alkoholové Shoty',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Citrón'
    },
    'hr': {
      'Caffè Espresso': 'Kava Espresso',
      'Caffè Decaffeinato': 'Kava bez Kofeina',
      "Caffè d'Orzo": 'Ječmena Kava',
      'Caffè Ginseng': 'Ginzeng Kava',
      'Caffè Corretto': 'Kava s Grappom',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Topli Čaj',
      'Infusi': 'Biljni Čaj',
      'Cioccolata Calda': 'Topla Čokolada',
      'Acqua Naturale 1 L': 'Negazirana Voda 1 L',
      'Acqua Gassata 1 L': 'Gazirana Voda 1 L',
      'Estathé Limone': 'Ledeni Čaj Limun',
      'Estathé Pesca': 'Ledeni Čaj Breskva',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limun',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Voćni Sok',
      'Birra Bottiglia 33 cl': 'Pivo Boca 33 cl',
      'Birra Analcolica': 'Bezalkoholno Pivo',
      'Digestivi': 'Digestivi',
      'Shot Alcolici': 'Alkoholni Shotovi',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Limun'
    },
    'sr': {
      'Caffè Espresso': 'Kafa Espreso',
      'Caffè Decaffeinato': 'Kafa bez Kofeina',
      "Caffè d'Orzo": 'Ječmena Kafa',
      'Caffè Ginseng': 'Ginzeng Kafa',
      'Caffè Corretto': 'Kafa sa Grappom',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Topli Čaj',
      'Infusi': 'Biljni Čaj',
      'Cioccolata Calda': 'Topla Čokolada',
      'Acqua Naturale 1 L': 'Negazirana Voda 1 L',
      'Acqua Gassata 1 L': 'Gazirana Voda 1 L',
      'Estathé Limone': 'Ledeni Čaj Limun',
      'Estathé Pesca': 'Ledeni Čaj Breskva',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limun',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Voćni Sok',
      'Birra Bottiglia 33 cl': 'Pivo Flaša 33 cl',
      'Birra Analcolica': 'Bezalkoholno Pivo',
      'Digestivi': 'Digestivi',
      'Shot Alcolici': 'Alkoholni Šotovi',
      'Ricard': 'Rikar',
      'Whiskey': 'Viski',
      'Whisky & Coca': 'Viski & Kola',
      'Rhum & Coca': 'Rum & Kola',
      'Gin Tonic': 'Džin Tonik',
      'Gin Lemon': 'Džin Limun'
    },
    'sl': {
      'Caffè Espresso': 'Kava Espresso',
      'Caffè Decaffeinato': 'Brezkofeinska Kava',
      "Caffè d'Orzo": 'Ječmenova Kava',
      'Caffè Ginseng': 'Ginsenova Kava',
      'Caffè Corretto': 'Kava z Grappa',
      'Caffè Latte': 'Café Latte',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Topel Čaj',
      'Infusi': 'Zeliščni Čaj',
      'Cioccolata Calda': 'Vroča Čokolada',
      'Acqua Naturale 1 L': 'Negazirana Voda 1 L',
      'Acqua Gassata 1 L': 'Gazirana Voda 1 L',
      'Estathé Limone': 'Ledeni Čaj Limona',
      'Estathé Pesca': 'Ledeni Čaj Breskev',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limona',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Sadni Sok',
      'Birra Bottiglia 33 cl': 'Stekleničeno Pivo 33 cl',
      'Birra Analcolica': 'Brezalkoholno Pivo',
      'Digestivi': 'Digestivi',
      'Shot Alcolici': 'Alkoholni Shoti',
      'Ricard': 'Ricard',
      'Whiskey': 'Whisky',
      'Whisky & Coca': 'Whisky & Cola',
      'Rhum & Coca': 'Rum & Cola',
      'Gin Tonic': 'Gin Tonik',
      'Gin Lemon': 'Gin Limona'
    },
    'tr': {
      'Caffè Espresso': 'Espresso Kahve',
      'Caffè Decaffeinato': 'Kafeinsiz Kahve',
      "Caffè d'Orzo": 'Arpa Kahvesi',
      'Caffè Ginseng': 'Ginseng Kahvesi',
      'Caffè Corretto': "Grappa'lı Kahve",
      'Caffè Latte': 'Sütlü Kahve',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Sıcak Çay',
      'Infusi': 'Bitki Çayı',
      'Cioccolata Calda': 'Sıcak Çikolata',
      'Acqua Naturale 1 L': 'Doğal Su 1 L',
      'Acqua Gassata 1 L': 'Gazlı Su 1 L',
      'Estathé Limone': 'Soğuk Çay Limon',
      'Estathé Pesca': 'Soğuk Çay Şeftali',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Limon',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Meyve Suyu',
      'Birra Bottiglia 33 cl': 'Şişe Bira 33 cl',
      'Birra Analcolica': 'Alkolsüz Bira',
      'Digestivi': 'Digestifler',
      'Shot Alcolici': 'Alkol Şotları',
      'Ricard': 'Ricard',
      'Whiskey': 'Viski',
      'Whisky & Coca': 'Viski & Kola',
      'Rhum & Coca': 'Rom & Kola',
      'Gin Tonic': 'Cin Tonik',
      'Gin Lemon': 'Cin Limon'
    },
    'ar': {
      'Caffè Espresso': 'قهوة إسبريسو',
      'Caffè Decaffeinato': 'قهوة منزوعة الكافيين',
      "Caffè d'Orzo": 'قهوة الشعير',
      'Caffè Ginseng': 'قهوة الجنسنغ',
      'Caffè Corretto': 'قهوة بالغراپا',
      'Caffè Latte': 'كافيه لاتيه',
      'Latte Macchiato': 'لاتيه ماكياتو',
      'Tè Caldo': 'شاي ساخن',
      'Infusi': 'شاي أعشاب',
      'Cioccolata Calda': 'شوكولاتة ساخنة',
      'Acqua Naturale 1 L': 'مياه طبيعية 1 لتر',
      'Acqua Gassata 1 L': 'مياه غازية 1 لتر',
      'Estathé Limone': 'شاي بارد بالليمون',
      'Estathé Pesca': 'شاي بارد بالخوخ',
      'Schweppes': 'شويبس',
      'Schweppes Lemon': 'شويبس ليمون',
      'Crodino': 'كرودينو',
      'Sanbitter': 'سانبيتر',
      'Succo di Frutta': 'عصير فواكه',
      'Birra Bottiglia 33 cl': 'بيرة زجاجة 33 سل',
      'Birra Analcolica': 'بيرة خالية من الكحول',
      'Digestivi': 'مشروبات هضمية',
      'Shot Alcolici': 'شوتات كحولية',
      'Ricard': 'ريكار',
      'Whiskey': 'ويسكي',
      'Whisky & Coca': 'ويسكي & كولا',
      'Rhum & Coca': 'روم & كولا',
      'Gin Tonic': 'جن & توني',
      'Gin Lemon': 'جن & ليمون'
    },
    'zh-CN': {
      'Caffè Espresso': '意式浓缩咖啡',
      'Caffè Decaffeinato': '低咖啡因咖啡',
      "Caffè d'Orzo": '大麦咖啡',
      'Caffè Ginseng': '人参咖啡',
      'Caffè Corretto': '格拉帕咖啡',
      'Caffè Latte': '拿铁咖啡',
      'Latte Macchiato': '玛奇朵',
      'Tè Caldo': '热茶',
      'Infusi': '花草茶',
      'Cioccolata Calda': '热巧克力',
      'Acqua Naturale 1 L': '天然矿泉水 1升',
      'Acqua Gassata 1 L': '气泡水 1升',
      'Estathé Limone': '柠檬冰茶',
      'Estathé Pesca': '桃子冰茶',
      'Schweppes': '施韦普斯',
      'Schweppes Lemon': '施韦普斯柠檬',
      'Crodino': '克罗迪诺',
      'Sanbitter': '桑比特',
      'Succo di Frutta': '果汁',
      'Birra Bottiglia 33 cl': '瓶装啤酒 33克拉',
      'Birra Analcolica': '无酒精啤酒',
      'Digestivi': '助消化饮品',
      'Shot Alcolici': '烈酒一口杯',
      'Ricard': '力加',
      'Whiskey': '威士忌',
      'Whisky & Coca': '威士忌 & 可乐',
      'Rhum & Coca': '朗姆酒 & 可乐',
      'Gin Tonic': '金汤力',
      'Gin Lemon': '金柠檬'
    },
    'ja': {
      'Caffè Espresso': 'エスプレッソ',
      'Caffè Decaffeinato': 'デカフェコーヒー',
      "Caffè d'Orzo": '大麦コーヒー',
      'Caffè Ginseng': '高麗人参コーヒー',
      'Caffè Corretto': 'グラッパ入りコーヒー',
      'Caffè Latte': 'カフェラテ',
      'Latte Macchiato': 'ラテマキアート',
      'Tè Caldo': 'ホットティー',
      'Infusi': 'ハーブティー',
      'Cioccolata Calda': 'ホットチョコレート',
      'Acqua Naturale 1 L': 'ミネラルウォーター 1L',
      'Acqua Gassata 1 L': '炭酸水 1L',
      'Estathé Limone': 'レモンアイスティー',
      'Estathé Pesca': '桃アイスティー',
      'Schweppes': 'シュウェップス',
      'Schweppes Lemon': 'シュウェップス レモン',
      'Crodino': 'クロディーノ',
      'Sanbitter': 'サンビター',
      'Succo di Frutta': 'フルーツジュース',
      'Birra Bottiglia 33 cl': 'ビール瓶 33cl',
      'Birra Analcolica': 'ノンアルコールビール',
      'Digestivi': '食後酒',
      'Shot Alcolici': 'アルコールショット',
      'Ricard': 'リカール',
      'Whiskey': 'ウイスキー',
      'Whisky & Coca': 'ウイスキー & コーラ',
      'Rhum & Coca': 'ラム & コーラ',
      'Gin Tonic': 'ジン & トニック',
      'Gin Lemon': 'ジン & レモン'
    },
    'ko': {
      'Caffè Espresso': '에스프레소',
      'Caffè Decaffeinato': '디카페인 커피',
      "Caffè d'Orzo": '보리 커피',
      'Caffè Ginseng': '인삼 커피',
      'Caffè Corretto': '그라파 커피',
      'Caffè Latte': '카페 라테',
      'Latte Macchiato': '라테 마키아토',
      'Tè Caldo': '따뜻한 차',
      'Infusi': '허브티',
      'Cioccolata Calda': '핫 초콜릿',
      'Acqua Naturale 1 L': '생수 1L',
      'Acqua Gassata 1 L': '탄산수 1L',
      'Estathé Limone': '레몬 아이스티',
      'Estathé Pesca': '복숭아 아이스티',
      'Schweppes': '슈웹스',
      'Schweppes Lemon': '슈웹스 레몬',
      'Crodino': '크로디노',
      'Sanbitter': '산비터',
      'Succo di Frutta': '과일 주스',
      'Birra Bottiglia 33 cl': '병 맥주 33cl',
      'Birra Analcolica': '무알코올 맥주',
      'Digestivi': '소화 증진 주류',
      'Shot Alcolici': '알코올 샷',
      'Ricard': '리카르',
      'Whiskey': '위스키',
      'Whisky & Coca': '위스키 & 콜라',
      'Rhum & Coca': '럼 & 콜라',
      'Gin Tonic': '진 토닉',
      'Gin Lemon': '진 레몬'
    },
    'hi': {
      'Caffè Espresso': 'एस्प्रेसो कॉफ़ी',
      'Caffè Decaffeinato': 'डिकैफ़ कॉफ़ी',
      "Caffè d'Orzo": 'जौ कॉफ़ी',
      'Caffè Ginseng': 'जिनसेंग कॉफ़ी',
      'Caffè Corretto': 'ग्रापा के साथ कॉफ़ी',
      'Caffè Latte': 'कैफ़े लाते',
      'Latte Macchiato': 'लाते मैकियाटो',
      'Tè Caldo': 'गर्म चाय',
      'Infusi': 'हर्बल चाय',
      'Cioccolata Calda': 'गर्म चॉकलेट',
      'Acqua Naturale 1 L': 'सादा पानी 1 लीटर',
      'Acqua Gassata 1 L': 'कार्बोनेटेड पानी 1 लीटर',
      'Estathé Limone': 'आइस्ड टी नींबू',
      'Estathé Pesca': 'आइस्ड टी आड़ू',
      'Schweppes': 'श्वेप्स',
      'Schweppes Lemon': 'श्वेप्स नींबू',
      'Crodino': 'क्रोदिनो',
      'Sanbitter': 'सैनबिटर',
      'Succo di Frutta': 'फलों का जूस',
      'Birra Bottiglia 33 cl': 'बीयर बोतल 33 cl',
      'Birra Analcolica': 'नॉन-अल्कोहलिक बीयर',
      'Digestivi': 'पाचक पेय',
      'Shot Alcolici': 'अल्कोहल शॉट्स',
      'Ricard': 'रिकार',
      'Whiskey': 'व्हिस्की',
      'Whisky & Coca': 'व्हिस्की & कोला',
      'Rhum & Coca': 'रम & कोला',
      'Gin Tonic': 'जिन टॉनिक',
      'Gin Lemon': 'जिन नींबू'
    },
    'bn': {
      'Caffè Espresso': 'এস্প্রেসো কফি',
      'Caffè Decaffeinato': 'ডিক্যাফ কফি',
      "Caffè d'Orzo": 'বার্লি কফি',
      'Caffè Ginseng': 'জিনসেং কফি',
      'Caffè Corretto': 'গ্রাপা সহ কফি',
      'Caffè Latte': 'ক্যাফে লাতে',
      'Latte Macchiato': 'লাতে মাকিয়াতো',
      'Tè Caldo': 'গরম চা',
      'Infusi': 'হার্বাল চা',
      'Cioccolata Calda': 'গরম চকোলেট',
      'Acqua Naturale 1 L': 'সাদা পানি ১ লিটার',
      'Acqua Gassata 1 L': 'কার্বনেটেড পানি ১ লিটার',
      'Estathé Limone': 'আইসড টি লেবু',
      'Estathé Pesca': 'আইসড টি পিচ',
      'Schweppes': 'শোয়েপস',
      'Schweppes Lemon': 'শোয়েপস লেবু',
      'Crodino': 'ক্রোদিনো',
      'Sanbitter': 'স্যানবিটার',
      'Succo di Frutta': 'ফলের জুস',
      'Birra Bottiglia 33 cl': 'বোতল বিয়ার ৩৩ ক্লি',
      'Birra Analcolica': 'নন-অ্যালকোহলিক বিয়ার',
      'Digestivi': 'পাচক পানীয়',
      'Shot Alcolici': 'অ্যালকোহল শট',
      'Ricard': 'রিকার্ড',
      'Whiskey': 'হুইস্কি',
      'Whisky & Coca': 'হুইস্কি & কোলা',
      'Rhum & Coca': 'রাম & কোলা',
      'Gin Tonic': 'জিন টনিক',
      'Gin Lemon': 'জিন লেবু'
    },
    'ur': {
      'Caffè Espresso': 'ایسپریسو کافی',
      'Caffè Decaffeinato': 'بغیر کیفین کافی',
      "Caffè d'Orzo": 'جَو کافی',
      'Caffè Ginseng': 'جنسنگ کافی',
      'Caffè Corretto': 'گراپا کے ساتھ کافی',
      'Caffè Latte': 'کیفے لاتے',
      'Latte Macchiato': 'لاتے ماکیاتو',
      'Tè Caldo': 'گرم چائے',
      'Infusi': 'جڑی بوٹی چائے',
      'Cioccolata Calda': 'گرم چاکلیٹ',
      'Acqua Naturale 1 L': 'سادہ پانی ۱ لیٹر',
      'Acqua Gassata 1 L': 'کاربونیٹڈ پانی ۱ لیٹر',
      'Estathé Limone': 'آئسڈ ٹی لیموں',
      'Estathé Pesca': 'آئسڈ ٹی آڑو',
      'Schweppes': 'شوئپس',
      'Schweppes Lemon': 'شوئپس لیموں',
      'Crodino': 'کرودینو',
      'Sanbitter': 'سان بیٹر',
      'Succo di Frutta': 'پھلوں کا جوس',
      'Birra Bottiglia 33 cl': 'بوتل بیئر ۳۳ کل',
      'Birra Analcolica': 'بغیر الکحل بیئر',
      'Digestivi': 'ہاضمہ مشروبات',
      'Shot Alcolici': 'الکوہل شاٹ',
      'Ricard': 'ریکارڈ',
      'Whiskey': 'وسکی',
      'Whisky & Coca': 'وسکی & کولا',
      'Rhum & Coca': 'رم & کولا',
      'Gin Tonic': 'جن ٹانک',
      'Gin Lemon': 'جن لیموں'
    },
    'fa': {
      'Caffè Espresso': 'اسپرسو',
      'Caffè Decaffeinato': 'قهوه بدون کافئین',
      "Caffè d'Orzo": 'قهوه جو',
      'Caffè Ginseng': 'قهوه جینسنگ',
      'Caffè Corretto': 'قهوه با گراپا',
      'Caffè Latte': 'کافه لاته',
      'Latte Macchiato': 'لاته ماکیاتو',
      'Tè Caldo': 'چای گرم',
      'Infusi': 'دمنوش گیاهی',
      'Cioccolata Calda': 'شکلات داغ',
      'Acqua Naturale 1 L': 'آب معدنی ۱ لیتر',
      'Acqua Gassata 1 L': 'آب گازدار ۱ لیتر',
      'Estathé Limone': 'چای سرد لیمو',
      'Estathé Pesca': 'چای سرد هلو',
      'Schweppes': 'شوپس',
      'Schweppes Lemon': 'شوپس لیمو',
      'Crodino': 'کرودینو',
      'Sanbitter': 'سان‌بیتر',
      'Succo di Frutta': 'آب میوه',
      'Birra Bottiglia 33 cl': 'آبجو بطری ۳۳ سی‌سی',
      'Birra Analcolica': 'آبجو بدون الکل',
      'Digestivi': 'نوشیدنی گوارشی',
      'Shot Alcolici': 'شات الکلی',
      'Ricard': 'ریکارد',
      'Whiskey': 'ویسکی',
      'Whisky & Coca': 'ویسکی & کولا',
      'Rhum & Coca': 'رام & کولا',
      'Gin Tonic': 'جین تونیک',
      'Gin Lemon': 'جین لیمون'
    },
    'vi': {
      'Caffè Espresso': 'Cà Phê Espresso',
      'Caffè Decaffeinato': 'Cà Phê Không Caffeine',
      "Caffè d'Orzo": 'Cà Phê Lúa Mạch',
      'Caffè Ginseng': 'Cà Phê Nhân Sâm',
      'Caffè Corretto': 'Cà Phê Pha Rượu Grappa',
      'Caffè Latte': 'Cà Phê Sữa',
      'Latte Macchiato': 'Latte Macchiato',
      'Tè Caldo': 'Trà Nóng',
      'Infusi': 'Trà Thảo Mộc',
      'Cioccolata Calda': 'Sô Cô La Nóng',
      'Acqua Naturale 1 L': 'Nước Lọc 1 lít',
      'Acqua Gassata 1 L': 'Nước Có Ga 1 lít',
      'Estathé Limone': 'Trà Đá Chanh',
      'Estathé Pesca': 'Trà Đá Đào',
      'Schweppes': 'Schweppes',
      'Schweppes Lemon': 'Schweppes Chanh',
      'Crodino': 'Crodino',
      'Sanbitter': 'Sanbitter',
      'Succo di Frutta': 'Nước Ép Trái Cây',
      'Birra Bottiglia 33 cl': 'Bia Chai 33 cl',
      'Birra Analcolica': 'Bia Không Cồn',
      'Digestivi': 'Rượu Tiêu Hóa',
      'Shot Alcolici': 'Shot Rượu',
      'Ricard': 'Ricard',
      'Whiskey': 'Whiskey',
      'Whisky & Coca': 'Whisky & Coca',
      'Rhum & Coca': 'Rum & Coca',
      'Gin Tonic': 'Gin Tonic',
      'Gin Lemon': 'Gin Chanh'
    },
    'th': {
      'Caffè Espresso': 'กาแฟเอสเปรสโซ',
      'Caffè Decaffeinato': 'กาแฟไร้คาเฟอีน',
      "Caffè d'Orzo": 'กาแฟข้าวบาร์เลย์',
      'Caffè Ginseng': 'กาแฟโสม',
      'Caffè Corretto': 'กาแฟใส่กราปปา',
      'Caffè Latte': 'คาเฟ่ลาเต้',
      'Latte Macchiato': 'ลาเต้มัคคิอาโต้',
      'Tè Caldo': 'ชาร้อน',
      'Infusi': 'ชาสมุนไพร',
      'Cioccolata Calda': 'ช็อกโกแลตร้อน',
      'Acqua Naturale 1 L': 'น้ำเปล่า 1 ลิตร',
      'Acqua Gassata 1 L': 'น้ำอัดลม 1 ลิตร',
      'Estathé Limone': 'ชาเย็นมะนาว',
      'Estathé Pesca': 'ชาเย็นพีช',
      'Schweppes': 'ชเวปส์',
      'Schweppes Lemon': 'ชเวปส์มะนาว',
      'Crodino': 'โครดิโน',
      'Sanbitter': 'ซานบิทเทอร์',
      'Succo di Frutta': 'น้ำผลไม้',
      'Birra Bottiglia 33 cl': 'เบียร์ขวด 33 ซล.',
      'Birra Analcolica': 'เบียร์ไม่มีแอลกอฮอล์',
      'Digestivi': 'เครื่องดื่มช่วยย่อย',
      'Shot Alcolici': 'ช็อตแอลกอฮอล์',
      'Ricard': 'ริการ์ด',
      'Whiskey': 'วิสกี้',
      'Whisky & Coca': 'วิสกี้ & โคล่า',
      'Rhum & Coca': 'รัม & โคล่า',
      'Gin Tonic': 'จิน โทนิค',
      'Gin Lemon': 'จิน มะนาว'
    }
  };

  // Merge into existing BAR_TRANS (correct axis: dish-name -> lang -> translation)
  if (typeof BAR_TRANS !== 'undefined') {
    var mergedCount = 0;
    Object.keys(PATCH).forEach(function (lang) {
      Object.keys(PATCH[lang]).forEach(function (dishName) {
        if (!BAR_TRANS[dishName]) BAR_TRANS[dishName] = {};
        BAR_TRANS[dishName][lang] = PATCH[lang][dishName];
        mergedCount++;
      });
    });
    console.log('[bar_trans_patch] Merged ' + mergedCount + ' dish translations across ' + Object.keys(PATCH).length + ' languages into BAR_TRANS.');
  } else {
    console.warn('[bar_trans_patch] BAR_TRANS not found — load this AFTER the BAR_TRANS block.');
  }

  // ------------------------------------------------------------
  // BAR_GROUP_TITLES — same 30 languages for the new section headers
  // (acqua, bibite_group, analcolici, succhi, aperitivi, spritz,
  //  longdrink, digestivi, shot)
  // ------------------------------------------------------------
  var GROUP_PATCH = {
    'nl': { acqua: '💧 Water', bibite_group: '🥤 Frisdranken', analcolici: '🍋 Alcoholvrij', succhi: '🧃 Sappen', aperitivi: '🍸 Aperitieven', spritz: '🥂 Spritz & Klassieke Cocktails — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestieven', shot: '🥃 Shots' },
    'es': { acqua: '💧 Agua', bibite_group: '🥤 Bebidas', analcolici: '🍋 Sin Alcohol', succhi: '🧃 Zumos', aperitivi: '🍸 Aperitivos', spritz: '🥂 Spritz & Cócteles Clásicos — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestivos', shot: '🥃 Chupitos' },
    'pt': { acqua: '💧 Água', bibite_group: '🥤 Bebidas', analcolici: '🍋 Sem Álcool', succhi: '🧃 Sumos', aperitivi: '🍸 Aperitivos', spritz: '🥂 Spritz & Cocktails Clássicos — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestivos', shot: '🥃 Shots' },
    'ru': { acqua: '💧 Вода', bibite_group: '🥤 Напитки', analcolici: '🍋 Безалкогольные', succhi: '🧃 Соки', aperitivi: '🍸 Аперитивы', spritz: '🥂 Спритц и Классические Коктейли — €6,00', longdrink: '🥃 Лонг Дринк — €8,00', digestivi: '🥃 Дижестивы', shot: '🥃 Шоты' },
    'pl': { acqua: '💧 Woda', bibite_group: '🥤 Napoje', analcolici: '🍋 Bezalkoholowe', succhi: '🧃 Soki', aperitivi: '🍸 Aperitify', spritz: '🥂 Spritz i Klasyczne Koktajle — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestify', shot: '🥃 Shoty' },
    'uk': { acqua: '💧 Вода', bibite_group: '🥤 Напої', analcolici: '🍋 Безалкогольні', succhi: '🧃 Соки', aperitivi: '🍸 Аперитиви', spritz: '🥂 Спритц і Класичні Коктейлі — €6,00', longdrink: '🥃 Лонг Дрінк — €8,00', digestivi: '🥃 Дижестиви', shot: '🥃 Шоти' },
    'ro': { acqua: '💧 Apă', bibite_group: '🥤 Băuturi', analcolici: '🍋 Fără Alcool', succhi: '🧃 Sucuri', aperitivi: '🍸 Aperitive', spritz: '🥂 Spritz & Cocktailuri Clasice — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestive', shot: '🥃 Shoturi' },
    'sv': { acqua: '💧 Vatten', bibite_group: '🥤 Drycker', analcolici: '🍋 Alkoholfritt', succhi: '🧃 Juicer', aperitivi: '🍸 Aperitif', spritz: '🥂 Spritz & Klassiska Cocktails — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestif', shot: '🥃 Shots' },
    'da': { acqua: '💧 Vand', bibite_group: '🥤 Drikkevarer', analcolici: '🍋 Alkoholfrit', succhi: '🧃 Juice', aperitivi: '🍸 Aperitif', spritz: '🥂 Spritz & Klassiske Cocktails — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestif', shot: '🥃 Shots' },
    'no': { acqua: '💧 Vann', bibite_group: '🥤 Drikke', analcolici: '🍋 Alkoholfritt', succhi: '🧃 Juice', aperitivi: '🍸 Aperitiff', spritz: '🥂 Spritz & Klassiske Cocktailer — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestif', shot: '🥃 Shots' },
    'fi': { acqua: '💧 Vesi', bibite_group: '🥤 Juomat', analcolici: '🍋 Alkoholittomat', succhi: '🧃 Mehut', aperitivi: '🍸 Aperitiivit', spritz: '🥂 Spritz & Klassiset Cocktailit — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestiivit', shot: '🥃 Shotit' },
    'el': { acqua: '💧 Νερό', bibite_group: '🥤 Αναψυκτικά', analcolici: '🍋 Χωρίς Αλκοόλ', succhi: '🧃 Χυμοί', aperitivi: '🍸 Απεριτίφ', spritz: '🥂 Spritz & Κλασικά Κοκτέιλ — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Πεπτικά', shot: '🥃 Σφηνάκια' },
    'cs': { acqua: '💧 Voda', bibite_group: '🥤 Nápoje', analcolici: '🍋 Nealkoholické', succhi: '🧃 Džusy', aperitivi: '🍸 Aperitivy', spritz: '🥂 Spritz & Klasické Koktejly — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestivy', shot: '🥃 Shoty' },
    'hu': { acqua: '💧 Víz', bibite_group: '🥤 Üdítők', analcolici: '🍋 Alkoholmentes', succhi: '🧃 Gyümölcslevek', aperitivi: '🍸 Aperitifek', spritz: '🥂 Spritz & Klasszikus Koktélok — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestifek', shot: '🥃 Shotok' },
    'bg': { acqua: '💧 Вода', bibite_group: '🥤 Напитки', analcolici: '🍋 Безалкохолни', succhi: '🧃 Сокове', aperitivi: '🍸 Аперитиви', spritz: '🥂 Спритц & Класически Коктейли — €6,00', longdrink: '🥃 Лонг Дринк — €8,00', digestivi: '🥃 Дижестиви', shot: '🥃 Шотове' },
    'sk': { acqua: '💧 Voda', bibite_group: '🥤 Nápoje', analcolici: '🍋 Nealkoholické', succhi: '🧃 Džúsy', aperitivi: '🍸 Aperitívy', spritz: '🥂 Spritz & Klasické Koktaily — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestívy', shot: '🥃 Shoty' },
    'hr': { acqua: '💧 Voda', bibite_group: '🥤 Pića', analcolici: '🍋 Bezalkoholna', succhi: '🧃 Sokovi', aperitivi: '🍸 Aperitivi', spritz: '🥂 Spritz & Klasični Kokteli — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestivi', shot: '🥃 Shotovi' },
    'sr': { acqua: '💧 Вода', bibite_group: '🥤 Пића', analcolici: '🍋 Безалкохолна', succhi: '🧃 Сокови', aperitivi: '🍸 Аперитиви', spritz: '🥂 Сприц & Класични Коктели — €6,00', longdrink: '🥃 Лонг Дринк — €8,00', digestivi: '🥃 Дигестиви', shot: '🥃 Шотови' },
    'sl': { acqua: '💧 Voda', bibite_group: '🥤 Pijače', analcolici: '🍋 Brezalkoholno', succhi: '🧃 Sokovi', aperitivi: '🍸 Aperitivi', spritz: '🥂 Spritz & Klasični Kokteli — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestivi', shot: '🥃 Shoti' },
    'tr': { acqua: '💧 Su', bibite_group: '🥤 İçecekler', analcolici: '🍋 Alkolsüz', succhi: '🧃 Meyve Suları', aperitivi: '🍸 Aperitifler', spritz: '🥂 Spritz & Klasik Kokteyller — €6,00', longdrink: '🥃 Long Drink — €8,00', digestivi: '🥃 Digestifler', shot: '🥃 Shotlar' },
    'ar': { acqua: '💧 مياه', bibite_group: '🥤 مشروبات غازية', analcolici: '🍋 بدون كحول', succhi: '🧃 عصائر', aperitivi: '🍸 مقبلات كحولية', spritz: '🥂 سبريتز والكوكتيلات الكلاسيكية — €6.00', longdrink: '🥃 لونج درينك — €8.00', digestivi: '🥃 مشروبات هضمية', shot: '🥃 شوتات' },
    'zh-CN': { acqua: '💧 水', bibite_group: '🥤 软饮料', analcolici: '🍋 无酒精', succhi: '🧃 果汁', aperitivi: '🍸 开胃酒', spritz: '🥂 Spritz和经典鸡尾酒 — €6.00', longdrink: '🥃 长饮特调 — €8.00', digestivi: '🥃 助消化饮品', shot: '🥃 烈酒一口杯' },
    'ja': { acqua: '💧 水', bibite_group: '🥤 ソフトドリンク', analcolici: '🍋 ノンアルコール', succhi: '🧃 ジュース', aperitivi: '🍸 アペリティフ', spritz: '🥂 スプリッツ & クラシックカクテル — €6.00', longdrink: '🥃 ロングドリンク — €8.00', digestivi: '🥃 食後酒', shot: '🥃 アルコールショット' },
    'ko': { acqua: '💧 물', bibite_group: '🥤 청량음료', analcolici: '🍋 무알코올', succhi: '🧃 주스', aperitivi: '🍸 아페리티프', spritz: '🥂 스프리츠 & 클래식 칵테일 — €6.00', longdrink: '🥃 롱 드링크 — €8.00', digestivi: '🥃 소화 증진 주류', shot: '🥃 알코올 샷' },
    'hi': { acqua: '💧 पानी', bibite_group: '🥤 शीतल पेय', analcolici: '🍋 बिना अल्कोहल', succhi: '🧃 जूस', aperitivi: '🍸 एपेरिटिफ़', spritz: '🥂 स्प्रिट्ज़ और क्लासिक कॉकटेल — €6.00', longdrink: '🥃 लॉन्ग ड्रिंक — €8.00', digestivi: '🥃 पाचक पेय', shot: '🥃 अल्कोहल शॉट्स' },
    'bn': { acqua: '💧 পানি', bibite_group: '🥤 কোমল পানীয়', analcolici: '🍋 অ্যালকোহলবিহীন', succhi: '🧃 জুস', aperitivi: '🍸 এপেরিটিফ', spritz: '🥂 স্প্রিৎজ এবং ক্লাসিক ককটেল — €৬.০০', longdrink: '🥃 লং ড্রিংক — €৮.০০', digestivi: '🥃 পাচক পানীয়', shot: '🥃 অ্যালকোহল শট' },
    'ur': { acqua: '💧 پانی', bibite_group: '🥤 مشروبات', analcolici: '🍋 بغیر الکحل', succhi: '🧃 جوس', aperitivi: '🍸 ایپریٹف', spritz: '🥂 اسپرٹز اور کلاسک کاکٹیل — €6.00', longdrink: '🥃 لانگ ڈرنک — €8.00', digestivi: '🥃 ہاضمہ مشروبات', shot: '🥃 الکوہل شاٹ' },
    'fa': { acqua: '💧 آب', bibite_group: '🥤 نوشیدنی‌ها', analcolici: '🍋 بدون الکل', succhi: '🧃 آب میوه', aperitivi: '🍸 اپریتیف', spritz: '🥂 اسپریتز و کوکتل‌های کلاسیک — €6.00', longdrink: '🥃 لانگ درینک — €8.00', digestivi: '🥃 نوشیدنی گوارشی', shot: '🥃 شات الکلی' },
    'vi': { acqua: '💧 Nước', bibite_group: '🥤 Đồ Uống', analcolici: '🍋 Không Cồn', succhi: '🧃 Nước Ép', aperitivi: '🍸 Khai Vị Có Cồn', spritz: '🥂 Spritz & Cocktail Cổ Điển — €6.00', longdrink: '🥃 Long Drink — €8.00', digestivi: '🥃 Rượu Tiêu Hóa', shot: '🥃 Shot Rượu' },
    'th': { acqua: '💧 น้ำ', bibite_group: '🥤 เครื่องดื่ม', analcolici: '🍋 ไม่มีแอลกอฮอล์', succhi: '🧃 น้ำผลไม้', aperitivi: '🍸 อาเปอริทีฟ', spritz: '🥂 สปริตซ์ & ค็อกเทลคลาสสิก — €6.00', longdrink: '🥃 ลองดริงค์ — €8.00', digestivi: '🥃 เครื่องดื่มช่วยย่อย', shot: '🥃 ช็อตแอลกอฮอล์' }
  };
  if (typeof BAR_GROUP_TITLES !== 'undefined') {
    Object.keys(GROUP_PATCH).forEach(function (lang) {
      Object.keys(GROUP_PATCH[lang]).forEach(function (groupKey) {
        if (!BAR_GROUP_TITLES[groupKey]) BAR_GROUP_TITLES[groupKey] = {};
        BAR_GROUP_TITLES[groupKey][lang] = GROUP_PATCH[lang][groupKey];
      });
    });
    console.log('[bar_trans_patch] Merged ' + Object.keys(GROUP_PATCH).length + ' languages into BAR_GROUP_TITLES.');
  } else {
    console.warn('[bar_trans_patch] BAR_GROUP_TITLES not found — group headers were not patched.');
  }
})();
