/**
 * i18n_patch_extra.js
 * ---------------------------------------------------------------
 * Adds translations for recent menu changes to the existing
 * window.I18N_PATCH object (30 extra languages beyond IT/FR/EN/DE):
 *   1. "Pescato" / "Gamberoni" sauce options (Pescato o Gamberoni item)
 *   2. "nota_label" / "nota_ph" — the per-dish note field
 *   3. Fix pkg_degu_warn — remove "Saturday EVENING" -> "Saturday"
 *      (matches the same fix already made in the 4 core languages)
 *
 * Load this AFTER i18n_patch.js and BEFORE apply_i18n_patch.js /
 * connect_menu_i18n.js, so the merged data is available when the
 * page applies translations.
 * ---------------------------------------------------------------
 */
(function () {
  if (typeof window.I18N_PATCH === 'undefined') {
    console.warn('[i18n_patch_extra] window.I18N_PATCH not found — load this AFTER i18n_patch.js.');
    return;
  }

  // 1) Pescato / Gamberoni sauce translations (word for "Fish" / "Prawns")
  var SAUCE_ADD = {
    tr: { Pescato: 'Balık', Gamberoni: 'Karides' },
    bg: { Pescato: 'Риба', Gamberoni: 'Скариди' },
    sk: { Pescato: 'Ryba', Gamberoni: 'Krevety' },
    hr: { Pescato: 'Riba', Gamberoni: 'Kozice' },
    sr: { Pescato: 'Риба', Gamberoni: 'Шкампи' },
    sl: { Pescato: 'Riba', Gamberoni: 'Kozice' },
    ar: { Pescato: 'سمك', Gamberoni: 'جمبري' },
    'zh-CN': { Pescato: '鱼', Gamberoni: '虾' },
    ja: { Pescato: '魚', Gamberoni: '海老' },
    ko: { Pescato: '생선', Gamberoni: '새우' },
    hi: { Pescato: 'मछली', Gamberoni: 'झींगे' },
    bn: { Pescato: 'মাছ', Gamberoni: 'চিংড়ি' },
    ur: { Pescato: 'مچھلی', Gamberoni: 'جھینگے' },
    fa: { Pescato: 'ماهی', Gamberoni: 'میگو' },
    es: { Pescato: 'Pescado', Gamberoni: 'Langostinos' },
    pt: { Pescato: 'Peixe', Gamberoni: 'Camarões' },
    ru: { Pescato: 'Рыба', Gamberoni: 'Креветки' },
    nl: { Pescato: 'Vis', Gamberoni: 'Garnalen' },
    pl: { Pescato: 'Ryba', Gamberoni: 'Krewetki' },
    uk: { Pescato: 'Риба', Gamberoni: 'Креветки' },
    ro: { Pescato: 'Pește', Gamberoni: 'Creveți' },
    sv: { Pescato: 'Fisk', Gamberoni: 'Räkor' },
    da: { Pescato: 'Fisk', Gamberoni: 'Rejer' },
    no: { Pescato: 'Fisk', Gamberoni: 'Reker' },
    fi: { Pescato: 'Kala', Gamberoni: 'Katkaravut' },
    el: { Pescato: 'Ψάρι', Gamberoni: 'Γαρίδες' },
    cs: { Pescato: 'Ryba', Gamberoni: 'Krevety' },
    hu: { Pescato: 'Hal', Gamberoni: 'Garnélarák' },
    vi: { Pescato: 'Cá', Gamberoni: 'Tôm' },
    th: { Pescato: 'ปลา', Gamberoni: 'กุ้ง' }
  };

  // 2) Note field label / placeholder ("Note (optional)" / "e.g. no onion...")
  var NOTE_ADD = {
    tr: { nota_label: '📝 Not (isteğe bağlı)', nota_ph: 'Örn. soğansız...' },
    bg: { nota_label: '📝 Забележка (незадължително)', nota_ph: 'Напр. без лук...' },
    sk: { nota_label: '📝 Poznámka (voliteľné)', nota_ph: 'Napr. bez cibule...' },
    hr: { nota_label: '📝 Napomena (neobavezno)', nota_ph: 'Npr. bez luka...' },
    sr: { nota_label: '📝 Напомена (опционо)', nota_ph: 'Нпр. без лука...' },
    sl: { nota_label: '📝 Opomba (neobvezno)', nota_ph: 'Npr. brez čebule...' },
    ar: { nota_label: '📝 ملاحظة (اختياري)', nota_ph: 'مثال: بدون بصل...' },
    'zh-CN': { nota_label: '📝 备注（可选）', nota_ph: '例如：不要洋葱...' },
    ja: { nota_label: '📝 メモ（任意）', nota_ph: '例：玉ねぎ抜き...' },
    ko: { nota_label: '📝 메모 (선택 사항)', nota_ph: '예: 양파 빼고...' },
    hi: { nota_label: '📝 नोट (वैकल्पिक)', nota_ph: 'जैसे बिना प्याज...' },
    bn: { nota_label: '📝 নোট (ঐচ্ছিক)', nota_ph: 'যেমন পেঁয়াজ ছাড়া...' },
    ur: { nota_label: '📝 نوٹ (اختیاری)', nota_ph: 'مثلاً پیاز کے بغیر...' },
    fa: { nota_label: '📝 یادداشت (اختیاری)', nota_ph: 'مثلاً بدون پیاز...' },
    es: { nota_label: '📝 Nota (opcional)', nota_ph: 'Ej. sin cebolla...' },
    pt: { nota_label: '📝 Nota (opcional)', nota_ph: 'Ex. sem cebola...' },
    ru: { nota_label: '📝 Примечание (необязательно)', nota_ph: 'Напр. без лука...' },
    nl: { nota_label: '📝 Notitie (optioneel)', nota_ph: 'Bijv. zonder ui...' },
    pl: { nota_label: '📝 Notatka (opcjonalnie)', nota_ph: 'Np. bez cebuli...' },
    uk: { nota_label: '📝 Примітка (необов\'язково)', nota_ph: 'Напр. без цибулі...' },
    ro: { nota_label: '📝 Notă (opțional)', nota_ph: 'Ex. fără ceapă...' },
    sv: { nota_label: '📝 Anteckning (valfritt)', nota_ph: 'T.ex. utan lök...' },
    da: { nota_label: '📝 Note (valgfrit)', nota_ph: 'F.eks. uden løg...' },
    no: { nota_label: '📝 Notat (valgfritt)', nota_ph: 'F.eks. uten løk...' },
    fi: { nota_label: '📝 Huomautus (valinnainen)', nota_ph: 'Esim. ilman sipulia...' },
    el: { nota_label: '📝 Σημείωση (προαιρετικό)', nota_ph: 'π.χ. χωρίς κρεμμύδι...' },
    cs: { nota_label: '📝 Poznámka (nepovinné)', nota_ph: 'Např. bez cibule...' },
    hu: { nota_label: '📝 Megjegyzés (opcionális)', nota_ph: 'Pl. hagyma nélkül...' },
    vi: { nota_label: '📝 Ghi chú (không bắt buộc)', nota_ph: 'VD: không hành...' },
    th: { nota_label: '📝 หมายเหตุ (ไม่บังคับ)', nota_ph: 'เช่น ไม่ใส่หัวหอม...' }
  };

  // 3) pkg_degu_warn fix — remove the "Saturday EVENING" wording where present,
  //    matching the change already made to the 4 core languages (Sabato Sera -> Sabato).
  var DEGU_WARN_FIX = {
    bg: '⚠️ (*) Не се сервира в събота, неделя на обяд и в празничните дни.',
    sk: '⚠️ (*) Nepodáva sa v sobotu, v nedeľu na obed a počas sviatkov.',
    hr: '⚠️ (*) Ne poslužuje se subotom, nedjeljom u podne i praznikom.',
    sr: '⚠️ (*) Не служи се суботом, недељом за ручак и празницима.',
    sl: '⚠️ (*) Ni na voljo v soboto, nedeljo opoldne in ob praznikih.',
    ar: '⚠️ (*) لا يُقدَّم يوم السبت، وظهر الأحد، وأيام العطلات.',
    es: '⚠️ (*) No se sirve sábado, domingo a mediodía ni festivos.',
    pt: '⚠️ (*) Não servido ao sábado, domingo ao almoço e feriados.',
    ru: '⚠️ (*) Не подаётся в субботу, воскресенье днём и в праздники.',
    nl: '⚠️ (*) Niet geserveerd op zaterdag, zondagmiddag en feestdagen.',
    pl: '⚠️ (*) Niepodawane w sobotę, niedzielny obiad i w święta.',
    uk: '⚠️ (*) Не подається в суботу, неділю вдень та у свята.',
    ro: '⚠️ (*) Nu se servește sâmbătă, duminică la prânz și în sărbători.',
    sv: '⚠️ (*) Serveras ej lördag, söndagslunch och helgdagar.',
    da: '⚠️ (*) Serveres ikke lørdag, søndag frokost og på helligdage.',
    no: '⚠️ (*) Serveres ikke lørdag, søndag lunsj og på helligdager.',
    fi: '⚠️ (*) Ei tarjolla lauantaisin, sunnuntailounaalla eikä pyhäpäivinä.',
    el: '⚠️ (*) Δεν σερβίρεται Σάββατο, Κυριακή μεσημέρι και αργίες.',
    cs: '⚠️ (*) Neservíruje se v sobotu, v neděli k obědu a o svátcích.',
    hu: '⚠️ (*) Szombaton, vasárnap ebédidőben és ünnepnapokon nem szolgáljuk fel.'
  };

  // 4) "misc" — a generic Italian-text -> translation dictionary for
  //    static data-it labels that the connector's applyStaticUi() doesn't
  //    cover (bar sub-tabs, wine glass label, uve/grape labels, badge).
  //    connect_menu_i18n_extra.js reads this and swaps any [data-it]
  //    element whose current data-it value matches a key here.
  var MISC_ADD = {
    tr: { '🥤 Bibite': '🥤 İçecekler', '🍺 Birre': '🍺 Biralar', '🍸 Cocktail & Aperitivi': '🍸 Kokteyl & Aperitif', '☕ Caffetteria': '☕ Kafeterya', '⭐ Consigliato': '⭐ Önerilen', 'Secondo disponibilità': 'Mevcuda göre', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Domatesli, Tereyağı & Adaçaylı, Mantarlı veya Tereyağı & Kekikli', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Av Eti Soslu, Mantarlı veya Taze Pestolu', 'Al Burro e Salvia o alle Noci': 'Tereyağı & Adaçaylı veya Cevizli', 'Al Pesto Fresco o Primavera': 'Taze Pestolu veya Primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Mantarlı, Gorgonzola Peynirli veya Tereyağı & Adaçaylı', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Yeşil Biberli, Gorgonzolalı veya Izgara', 'Al Forno o alla Griglia — Secondo disponibilità': 'Fırında veya Izgara — Mevcuda göre', 'Dolce al caffè con mascarpone e cacao': 'Mascarpone ve kakaolu kahveli tatlı', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Meyve soslu kremalı vanilyalı tatlı', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Her gün ev yapımı — en fazla 3 çeşit seçimi', 'Disponibile con o senza alcol': 'Alkollü veya alkolsüz mevcuttur', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Tipik yemeklerimizle ve "Her Şey Dahil" formülüyle (her 4 kişiye 1 şişe ev şarabı) — mutfağın seçtiği 5 yemek', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, seçmeli 3 yemek, tatlı, kahve ve sindirim içeceği. İçecekler hariçtir.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, seçmeli 2 yemek, tatlı, kahve ve sindirim içeceği. İçecekler hariçtir.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Seçmeli bir yemek + ev yapımı dondurma + içecek', 'Carta dei Vini': 'Şarap Listesi', 'Carta dei Vini Digitale': 'Dijital Şarap Listesi', 'Tocca per sfogliare': 'Göz atmak için dokunun', 'Vini, Champagne e Vino della Casa': 'Şaraplar, Şampanya ve Ev Şarabı' },
    bg: { '🥤 Bibite': '🥤 Напитки', '🍺 Birre': '🍺 Бири', '🍸 Cocktail & Aperitivi': '🍸 Коктейли & Аперитиви', '☕ Caffetteria': '☕ Кафе', '⭐ Consigliato': '⭐ Препоръчано', 'Secondo disponibilità': 'Според наличността', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'С домати, масло и градински чай, гъби или масло и мащерка', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Със сос от дивеч, гъби или прясно песто', 'Al Burro e Salvia o alle Noci': 'С масло и градински чай или орехи', 'Al Pesto Fresco o Primavera': 'С прясно песто или примавера', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'С гъби, сирена и горгонзола или масло и градински чай', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Със зелен пипер, горгонзола или на скара', 'Al Forno o alla Griglia — Secondo disponibilità': 'На фурна или на скара — според наличността', 'Dolce al caffè con mascarpone e cacao': 'Кафяв десерт с маскарпоне и какао', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Кремообразен ванилов десерт с плодов сос', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Домашно приготвян всеки ден — до 3 вкуса по избор', 'Disponibile con o senza alcol': 'Предлага се с или без алкохол', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'С нашите типични ястия и формулата "Всичко включено" (1 бутилка домашно вино на 4 души) — 5 ястия избрани от кухнята', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 3 ястия по избор, десерт, кафе и дижестив. Напитките не са включени.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 2 ястия по избор, десерт, кафе и дижестив. Напитките не са включени.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Едно ястие по избор + домашен сладолед + напитка', 'Carta dei Vini': 'Винена карта', 'Carta dei Vini Digitale': 'Дигитална винена карта', 'Tocca per sfogliare': 'Докоснете за разглеждане', 'Vini, Champagne e Vino della Casa': 'Вина, шампанско и домашно вино' },
    sk: { '🥤 Bibite': '🥤 Nápoje', '🍺 Birre': '🍺 Pivá', '🍸 Cocktail & Aperitivi': '🍸 Koktaily & Aperitívy', '☕ Caffetteria': '☕ Kaviareň', '⭐ Consigliato': '⭐ Odporúčané', 'Secondo disponibilità': 'Podľa dostupnosti', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'S paradajkami, maslom a šalviou, hubami alebo maslom a tymianom', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'S poľovníckou omáčkou, hubami alebo čerstvým pestom', 'Al Burro e Salvia o alle Noci': 'S maslom a šalviou alebo vlašskými orechmi', 'Al Pesto Fresco o Primavera': 'S čerstvým pestom alebo primaverou', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'S hubami, syrmi a gorgonzolou alebo maslom a šalviou', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'So zeleným korením, gorgonzolou alebo na grile', 'Al Forno o alla Griglia — Secondo disponibilità': 'V rúre alebo na grile — podľa dostupnosti', 'Dolce al caffè con mascarpone e cacao': 'Kávový dezert s mascarpone a kakaom', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Krémový vanilkový dezert s ovocnou omáčkou', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Domáca výroba každý deň — max. 3 príchute na výber', 'Disponibile con o senza alcol': 'K dispozícii s alkoholom alebo bez', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'S našimi typickými jedlami a formulou "všetko v cene" (1 fľaša domáceho vína na 4 osoby) — 5 chodov vybraných kuchyňou', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitív, 3 chody podľa výberu, dezert, káva a digestív. Nápoje nie sú zahrnuté.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitív, 2 chody podľa výberu, dezert, káva a digestív. Nápoje nie sú zahrnuté.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Jedno jedlo podľa výberu + domáca zmrzlina + nápoj', 'Carta dei Vini': 'Vínny lístok', 'Carta dei Vini Digitale': 'Digitálny vínny lístok', 'Tocca per sfogliare': 'Kliknutím prezriete', 'Vini, Champagne e Vino della Casa': 'Vína, šampanské a domáce víno' },
    hr: { '🥤 Bibite': '🥤 Pića', '🍺 Birre': '🍺 Piva', '🍸 Cocktail & Aperitivi': '🍸 Kokteli & Aperitivi', '☕ Caffetteria': '☕ Kafić', '⭐ Consigliato': '⭐ Preporučeno', 'Secondo disponibilità': 'Ovisno o dostupnosti', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'S rajčicom, maslacem i kaduljom, gljivama ili maslacem i majčinom dušicom', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'S umakom od divljači, gljivama ili svježim pestom', 'Al Burro e Salvia o alle Noci': 'S maslacem i kaduljom ili orasima', 'Al Pesto Fresco o Primavera': 'Sa svježim pestom ili primaverom', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'S gljivama, sirevima i gorgonzolom ili maslacem i kaduljom', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Sa zelenim paprom, gorgonzolom ili na roštilju', 'Al Forno o alla Griglia — Secondo disponibilità': 'U pećnici ili na roštilju — ovisno o dostupnosti', 'Dolce al caffè con mascarpone e cacao': 'Kavni desert s mascarponeom i kakaom', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Kremasti vanilijev desert s voćnim umakom', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Domaći svaki dan — do 3 okusa po izboru', 'Disponibile con o senza alcol': 'Dostupno s alkoholom ili bez', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'S našim tipičnim jelima i formulom "sve uključeno" (1 boca kućnog vina na 4 osobe) — 5 jela po izboru kuhinje', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 3 jela po izboru, desert, kava i digestiv. Pića nisu uključena.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 2 jela po izboru, desert, kava i digestiv. Pića nisu uključena.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Jedno jelo po izboru + domaći sladoled + piće', 'Carta dei Vini': 'Vinska karta', 'Carta dei Vini Digitale': 'Digitalna vinska karta', 'Tocca per sfogliare': 'Dodirnite za pregled', 'Vini, Champagne e Vino della Casa': 'Vina, šampanjac i kućno vino' },
    sr: { '🥤 Bibite': '🥤 Пића', '🍺 Birre': '🍺 Пива', '🍸 Cocktail & Aperitivi': '🍸 Коктели & Аперитиви', '☕ Caffetteria': '☕ Кафе', '⭐ Consigliato': '⭐ Препоручено', 'Secondo disponibilità': 'У зависности од доступности', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Са парадајзом, путером и жалфијом, печуркама или путером и мајчином душицом', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Са сосом од дивљачи, печуркама или свежим пестом', 'Al Burro e Salvia o alle Noci': 'Са путером и жалфијом или орасима', 'Al Pesto Fresco o Primavera': 'Са свежим пестом или примавером', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Са печуркама, сиревима и горгонзолом или путером и жалфијом', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Са зеленим бибером, горгонзолом или на роштиљу', 'Al Forno o alla Griglia — Secondo disponibilità': 'У рерни или на роштиљу — у зависности од доступности', 'Dolce al caffè con mascarpone e cacao': 'Кафе десерт са маскарпонеом и какаом', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Кремасти ванила десерт са воћним сосом', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Домаће сваки дан — до 3 укуса по избору', 'Disponibile con o senza alcol': 'Доступно са или без алкохола', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Са нашим типичним јелима и формулом "све укључено" (1 боца кућног вина на 4 особе) — 5 јела по избору кухиње', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 3 јела по избору, десерт, кафа и дигестив. Пића нису укључена.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 2 јела по избору, десерт, кафа и дигестив. Пића нису укључена.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Једно јело по избору + домаћи сладолед + пиће', 'Carta dei Vini': 'Винска листа', 'Carta dei Vini Digitale': 'Дигитална винска листа', 'Tocca per sfogliare': 'Додирните за преглед', 'Vini, Champagne e Vino della Casa': 'Вина, шампањац и кућно вино' },
    sl: { '🥤 Bibite': '🥤 Pijače', '🍺 Birre': '🍺 Piva', '🍸 Cocktail & Aperitivi': '🍸 Kokteli & Aperitivi', '☕ Caffetteria': '☕ Kavarna', '⭐ Consigliato': '⭐ Priporočeno', 'Secondo disponibilità': 'Glede na razpoložljivost', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'S paradižnikom, maslom in žajbljem, gobami ali maslom in timijanom', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Z lovsko omako, gobami ali svežim pestom', 'Al Burro e Salvia o alle Noci': 'Z maslom in žajbljem ali orehi', 'Al Pesto Fresco o Primavera': 'S svežim pestom ali primavero', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Z gobami, siri in gorgonzolo ali maslom in žajbljem', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Z zelenim poprom, gorgonzolo ali na žaru', 'Al Forno o alla Griglia — Secondo disponibilità': 'V pečici ali na žaru — glede na razpoložljivost', 'Dolce al caffè con mascarpone e cacao': 'Kavna sladica z mascarponejem in kakavom', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Kremasta vaniljeva sladica s sadno omako', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Domače vsak dan — do 3 okusi po izbiri', 'Disponibile con o senza alcol': 'Na voljo z ali brez alkohola', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Z našimi tipičnimi jedmi in formulo "vse vključeno" (1 steklenica hišnega vina na 4 osebe) — 5 jedi po izbiri kuhinje', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 3 jedi po izbiri, sladica, kava in digestiv. Pijače niso vključene.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 2 jedi po izbiri, sladica, kava in digestiv. Pijače niso vključene.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Ena jed po izbiri + domač sladoled + pijača', 'Carta dei Vini': 'Vinska karta', 'Carta dei Vini Digitale': 'Digitalna vinska karta', 'Tocca per sfogliare': 'Dotaknite se za brskanje', 'Vini, Champagne e Vino della Casa': 'Vina, šampanjec in hišno vino' },
    ar: { '🥤 Bibite': '🥤 مشروبات', '🍺 Birre': '🍺 بيرة', '🍸 Cocktail & Aperitivi': '🍸 كوكتيلات ومقبلات', '☕ Caffetteria': '☕ مقهى', '⭐ Consigliato': '⭐ موصى به', 'Secondo disponibilità': 'حسب التوفر', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'بالطماطم، بالزبدة والمريمية، بالفطر أو بالزبدة والزعتر', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'بصلصة لحم الصيد، بالفطر أو بالبيستو الطازج', 'Al Burro e Salvia o alle Noci': 'بالزبدة والمريمية أو بالجوز', 'Al Pesto Fresco o Primavera': 'بالبيستو الطازج أو بريمافيرا', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'بالفطر، بالأجبان والجورجونزولا أو بالزبدة والمريمية', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'بالفلفل الأخضر، بالجورجونزولا أو مشوي', 'Al Forno o alla Griglia — Secondo disponibilità': 'في الفرن أو مشوي — حسب التوفر', 'Dolce al caffè con mascarpone e cacao': 'حلوى بالقهوة مع الماسكاربوني والكاكاو', 'Dolce cremoso alla vaniglia con salsa di frutta': 'حلوى كريمية بالفانيليا مع صلصة الفواكه', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'صنع منزلي يوميًا — بحد أقصى 3 نكهات للاختيار', 'Disponibile con o senza alcol': 'متوفر مع أو بدون كحول', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'مع أطباقنا التقليدية وصيغة "الكل شامل" (زجاجة نبيذ منزلي لكل 4 أشخاص) — 5 أطباق يختارها الشيف', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'مقبلات، 3 أطباق حسب الاختيار، حلوى، قهوة وهاضم. المشروبات غير مشمولة.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'مقبلات، طبقان حسب الاختيار، حلوى، قهوة وهاضم. المشروبات غير مشمولة.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'طبق واحد حسب الاختيار + مثلجات منزلية + مشروب', 'Carta dei Vini': 'قائمة النبيذ', 'Carta dei Vini Digitale': 'قائمة النبيذ الرقمية', 'Tocca per sfogliare': 'اضغط للتصفح', 'Vini, Champagne e Vino della Casa': 'نبيذ، شمبانيا ونبيذ منزلي' },
    'zh-CN': { '🥤 Bibite': '🥤 饮料', '🍺 Birre': '🍺 啤酒', '🍸 Cocktail & Aperitivi': '🍸 鸡尾酒和开胃酒', '☕ Caffetteria': '☕ 咖啡厅', '⭐ Consigliato': '⭐ 推荐', 'Secondo disponibilità': '视供应情况而定', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': '番茄酱、黄油鼠尾草酱、蘑菇酱或黄油百里香酱', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': '野味酱、蘑菇酱或新鲜香蒜酱', 'Al Burro e Salvia o alle Noci': '黄油鼠尾草酱或核桃酱', 'Al Pesto Fresco o Primavera': '新鲜香蒜酱或蔬菜酱', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': '蘑菇、奶酪与戈贡佐拉奶酪或黄油鼠尾草酱', 'Al Pepe Verde, al Gorgonzola o alla Griglia': '青胡椒、戈贡佐拉奶酪或炭烤', 'Al Forno o alla Griglia — Secondo disponibilità': '烤箱或炭烤 — 视供应情况而定', 'Dolce al caffè con mascarpone e cacao': '马斯卡彭咖啡可可甜点', 'Dolce cremoso alla vaniglia con salsa di frutta': '香草奶油甜点配果酱', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': '每日自制 — 最多可选3种口味', 'Disponibile con o senza alcol': '可选含酒精或不含酒精', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': '搭配我们的特色菜肴，采用"全包"套餐（每4人1瓶自酿酒）— 主厨精选5道菜', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': '开胃酒、自选3道菜、甜点、咖啡和餐后酒。不含饮品。', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': '开胃酒、自选2道菜、甜点、咖啡和餐后酒。不含饮品。', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': '自选一道菜 + 自制冰淇淋 + 饮品', 'Carta dei Vini': '酒单', 'Carta dei Vini Digitale': '数字酒单', 'Tocca per sfogliare': '点击浏览', 'Vini, Champagne e Vino della Casa': '葡萄酒、香槟和自酿酒' },
    ja: { '🥤 Bibite': '🥤 ドリンク', '🍺 Birre': '🍺 ビール', '🍸 Cocktail & Aperitivi': '🍸 カクテル & アペリティフ', '☕ Caffetteria': '☕ カフェ', '⭐ Consigliato': '⭐ おすすめ', 'Secondo disponibilità': '入荷状況によります', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'トマト、バター＆セージ、きのこ、またはバター＆タイム', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'ジビエソース、きのこ、または自家製バジルソース', 'Al Burro e Salvia o alle Noci': 'バター＆セージまたはくるみ', 'Al Pesto Fresco o Primavera': '自家製バジルソースまたは季節野菜', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'きのこ、チーズ＆ゴルゴンゾーラ、またはバター＆セージ', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'グリーンペッパー、ゴルゴンゾーラ、またはグリル', 'Al Forno o alla Griglia — Secondo disponibilità': 'オーブン焼きまたはグリル — 入荷状況によります', 'Dolce al caffè con mascarpone e cacao': 'マスカルポーネとカカオのコーヒーデザート', 'Dolce cremoso alla vaniglia con salsa di frutta': 'フルーツソース添えのクリーミーなバニラデザート', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': '毎日手作り — 最大3種類のフレーバーを選択可能', 'Disponibile con o senza alcol': 'アルコール入り・なしをお選びいただけます', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': '当店自慢の料理と「オールインクルーシブ」プラン（4名様につきハウスワイン1本）— シェフ厳選の5品', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'アペリティフ、お好きな料理3品、デザート、コーヒー、ディジェスティフ。ドリンクは含まれません。', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'アペリティフ、お好きな料理2品、デザート、コーヒー、ディジェスティフ。ドリンクは含まれません。', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'お好きな料理1品 + 自家製ジェラート + ドリンク', 'Carta dei Vini': 'ワインリスト', 'Carta dei Vini Digitale': 'デジタルワインリスト', 'Tocca per sfogliare': 'タップして閲覧', 'Vini, Champagne e Vino della Casa': 'ワイン、シャンパン、ハウスワイン' },
    ko: { '🥤 Bibite': '🥤 음료', '🍺 Birre': '🍺 맥주', '🍸 Cocktail & Aperitivi': '🍸 칵테일 & 아페리티프', '☕ Caffetteria': '☕ 카페', '⭐ Consigliato': '⭐ 추천', 'Secondo disponibilità': '재고에 따라 다름', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': '토마토, 버터&세이지, 버섯 또는 버터&타임', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': '엽육 소스, 버섯 또는 신선한 페스토', 'Al Burro e Salvia o alle Noci': '버터&세이지 또는 호두', 'Al Pesto Fresco o Primavera': '신선한 페스토 또는 프리마베라', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': '버섯, 치즈&고르곤졸라 또는 버터&세이지', 'Al Pepe Verde, al Gorgonzola o alla Griglia': '그린페퍼, 고르곤졸라 또는 그릴', 'Al Forno o alla Griglia — Secondo disponibilità': '오븐구이 또는 그릴 — 재고에 따라 다름', 'Dolce al caffè con mascarpone e cacao': '마스카르포네와 코코아를 곁들인 커피 디저트', 'Dolce cremoso alla vaniglia con salsa di frutta': '과일 소스를 곁들인 크리미한 바닐라 디저트', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': '매일 수제로 제작 — 최대 3가지 맛 선택 가능', 'Disponibile con o senza alcol': '알코올 유무 선택 가능', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': '저희의 전통 요리와 "올인클루시브" 구성 (4인당 하우스 와인 1병 포함) — 셰프가 선정한 5가지 코스', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': '아페리티프, 선택 요리 3개, 디저트, 커피 및 소화주. 음료는 포함되지 않습니다.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': '아페리티프, 선택 요리 2개, 디저트, 커피 및 소화주. 음료는 포함되지 않습니다.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': '선택 요리 1개 + 수제 젤라토 + 음료', 'Carta dei Vini': '와인 리스트', 'Carta dei Vini Digitale': '디지털 와인 리스트', 'Tocca per sfogliare': '눌러서 둘러보기', 'Vini, Champagne e Vino della Casa': '와인, 샴페인 및 하우스 와인' },
    hi: { '🥤 Bibite': '🥤 पेय', '🍺 Birre': '🍺 बीयर', '🍸 Cocktail & Aperitivi': '🍸 कॉकटेल और एपेरिटिफ़', '☕ Caffetteria': '☕ कैफ़े', '⭐ Consigliato': '⭐ अनुशंसित', 'Secondo disponibilità': 'उपलब्धता के अनुसार', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'टमाटर, मक्खन और ऋषि, मशरूम या मक्खन और थाइम के साथ', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'वाइल्ड मीट सॉस, मशरूम या ताज़ा पेस्टो के साथ', 'Al Burro e Salvia o alle Noci': 'मक्खन और ऋषि या अखरोट के साथ', 'Al Pesto Fresco o Primavera': 'ताज़ा पेस्टो या प्रिमावेरा के साथ', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'मशरूम, चीज़ और गोर्गोनज़ोला या मक्खन और ऋषि के साथ', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'हरी मिर्च, गोर्गोनज़ोला या ग्रिल्ड', 'Al Forno o alla Griglia — Secondo disponibilità': 'ओवन में या ग्रिल्ड — उपलब्धता के अनुसार', 'Dolce al caffè con mascarpone e cacao': 'मस्कारपोन और कोको के साथ कॉफी मिठाई', 'Dolce cremoso alla vaniglia con salsa di frutta': 'फल सॉस के साथ क्रीमी वेनिला मिठाई', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'रोज़ घर पर बनाया जाता है — अधिकतम 3 स्वाद चुनें', 'Disponibile con o senza alcol': 'शराब सहित या रहित उपलब्ध', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'हमारे पारंपरिक व्यंजनों और "सब कुछ शामिल" योजना के साथ (हर 4 व्यक्तियों के लिए 1 बोतल हाउस वाइन) — रसोई द्वारा चुने गए 5 व्यंजन', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'एपेरिटिफ़, 3 व्यंजन चुनने के लिए, मिठाई, कॉफी और डाइजेस्टिफ़। पेय शामिल नहीं हैं।', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'एपेरिटिफ़, 2 व्यंजन चुनने के लिए, मिठाई, कॉफी और डाइजेस्टिफ़। पेय शामिल नहीं हैं।', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'एक व्यंजन चुनने के लिए + घर का बना जिलेटो + पेय', 'Carta dei Vini': 'वाइन सूची', 'Carta dei Vini Digitale': 'डिजिटल वाइन सूची', 'Tocca per sfogliare': 'ब्राउज़ करने के लिए टैप करें', 'Vini, Champagne e Vino della Casa': 'वाइन, शैम्पेन और हाउस वाइन' },
    bn: { '🥤 Bibite': '🥤 পানীয়', '🍺 Birre': '🍺 বিয়ার', '🍸 Cocktail & Aperitivi': '🍸 ককটেল ও এপেরিটিফ', '☕ Caffetteria': '☕ ক্যাফে', '⭐ Consigliato': '⭐ প্রস্তাবিত', 'Secondo disponibilità': 'প্রাপ্যতার উপর নির্ভরশীল', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'টমেটো, মাখন ও সেজ, মাশরুম বা মাখন ও থাইম দিয়ে', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'বন্য মাংসের সস, মাশরুম বা তাজা পেস্তো দিয়ে', 'Al Burro e Salvia o alle Noci': 'মাখন ও সেজ বা আখরোট দিয়ে', 'Al Pesto Fresco o Primavera': 'তাজা পেস্তো বা প্রিমাভেরা দিয়ে', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'মাশরুম, চিজ ও গোরগনজোলা বা মাখন ও সেজ দিয়ে', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'সবুজ মরিচ, গোরগনজোলা বা গ্রিল করা', 'Al Forno o alla Griglia — Secondo disponibilità': 'ওভেনে বা গ্রিলে — প্রাপ্যতার উপর নির্ভরশীল', 'Dolce al caffè con mascarpone e cacao': 'মাসকারপনে ও কোকো সহ কফি ডেজার্ট', 'Dolce cremoso alla vaniglia con salsa di frutta': 'ফলের সস সহ ক্রিমি ভ্যানিলা ডেজার্ট', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'প্রতিদিন ঘরে তৈরি — সর্বোচ্চ ৩টি ফ্লেভার বেছে নিন', 'Disponibile con o senza alcol': 'অ্যালকোহল সহ বা ছাড়া পাওয়া যায়', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'আমাদের ঐতিহ্যবাহী পদ ও "সব কিছু অন্তর্ভুক্ত" (৪ জনের জন্য ১ বোতল হাউস ওয়াইন) — রান্নাঘরের বাছাই করা ৫টি পদ', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'অ্যাপেরিটিফ, বেছে নেওয়া ৩টি পদ, ডেজার্ট, কফি ও ডাইজেস্টিভ। পানীয় অন্তর্ভুক্ত নয়।', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'অ্যাপেরিটিফ, বেছে নেওয়া ২টি পদ, ডেজার্ট, কফি ও ডাইজেস্টিভ। পানীয় অন্তর্ভুক্ত নয়।', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'একটি পদ বেছে নিন + ঘরে তৈরি জেলাতো + পানীয়', 'Carta dei Vini': 'ওয়াইন তালিকা', 'Carta dei Vini Digitale': 'ডিজিটাল ওয়াইন তালিকা', 'Tocca per sfogliare': 'ব্রাউজ করতে ট্যাপ করুন', 'Vini, Champagne e Vino della Casa': 'ওয়াইন, শ্যাম্পেন ও হাউস ওয়াইন' },
    ur: { '🥤 Bibite': '🥤 مشروبات', '🍺 Birre': '🍺 بیئر', '🍸 Cocktail & Aperitivi': '🍸 کاکٹیل اور ایپریٹف', '☕ Caffetteria': '☕ کیفے', '⭐ Consigliato': '⭐ تجویز کردہ', 'Secondo disponibilità': 'دستیابی کے مطابق', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'ٹماٹر، مکھن اور سیج، مشروم یا مکھن اور تھائم کے ساتھ', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'وائلڈ گیم ساس، مشروم یا تازہ پیسٹو کے ساتھ', 'Al Burro e Salvia o alle Noci': 'مکھن اور سیج یا اخروٹ کے ساتھ', 'Al Pesto Fresco o Primavera': 'تازہ پیسٹو یا پریمیویرا کے ساتھ', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'مشروم، پنیر اور گورگونزولا یا مکھن اور سیج کے ساتھ', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'سبز مرچ، گورگونزولا یا گرل شدہ', 'Al Forno o alla Griglia — Secondo disponibilità': 'تندور میں یا گرل — دستیابی کے مطابق', 'Dolce al caffè con mascarpone e cacao': 'مسکارپونے اور کوکو کے ساتھ کافی میٹھا', 'Dolce cremoso alla vaniglia con salsa di frutta': 'پھلوں کی چٹنی کے ساتھ کریمی ونیلا میٹھا', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'روزانہ گھر پر تیار — زیادہ سے زیادہ 3 ذائقے منتخب کریں', 'Disponibile con o senza alcol': 'الکحل کے ساتھ یا بغیر دستیاب', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'ہمارے روایتی پکوانوں اور "سب کچھ شامل" فارمولے کے ساتھ (ہر 4 افراد کے لیے 1 بوتل ہاؤس وائن) — باورچی خانے کے منتخب کردہ 5 پکوان', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'ایپریٹف، منتخب کردہ 3 پکوان، میٹھا، کافی اور ڈائجسٹو۔ مشروبات شامل نہیں ہیں۔', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'ایپریٹف، منتخب کردہ 2 پکوان، میٹھا، کافی اور ڈائجسٹو۔ مشروبات شامل نہیں ہیں۔', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'ایک پکوان منتخب کریں + گھر کا بنا آئس کریم + مشروب', 'Carta dei Vini': 'شراب کی فہرست', 'Carta dei Vini Digitale': 'ڈیجیٹل شراب کی فہرست', 'Tocca per sfogliare': 'دیکھنے کے لیے ٹچ کریں', 'Vini, Champagne e Vino della Casa': 'شراب، شیمپین اور ہاؤس وائن' },
    fa: { '🥤 Bibite': '🥤 نوشیدنی‌ها', '🍺 Birre': '🍺 آبجو', '🍸 Cocktail & Aperitivi': '🍸 کوکتل و اپریتیف', '☕ Caffetteria': '☕ کافه', '⭐ Consigliato': '⭐ پیشنهادی', 'Secondo disponibilità': 'بر اساس موجودی', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'با گوجه‌فرنگی، کره و مریم‌گلی، قارچ یا کره و آویشن', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'با سس شکار، قارچ یا پستوی تازه', 'Al Burro e Salvia o alle Noci': 'با کره و مریم‌گلی یا گردو', 'Al Pesto Fresco o Primavera': 'با پستوی تازه یا پریماورا', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'با قارچ، پنیر و گورگونزولا یا کره و مریم‌گلی', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'با فلفل سبز، گورگونزولا یا کبابی', 'Al Forno o alla Griglia — Secondo disponibilità': 'در فر یا کبابی — بر اساس موجودی', 'Dolce al caffè con mascarpone e cacao': 'دسر قهوه با ماسکارپونه و کاکائو', 'Dolce cremoso alla vaniglia con salsa di frutta': 'دسر خامه‌ای وانیلی با سس میوه', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'روزانه خانگی — حداکثر ۳ طعم قابل انتخاب', 'Disponibile con o senza alcol': 'با یا بدون الکل موجود است', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'با غذاهای سنتی ما و طرح "همه‌چیز شامل" (۱ بطری شراب خانگی برای هر ۴ نفر) — ۵ غذای انتخابی آشپزخانه', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'اپریتیف، ۳ غذای انتخابی، دسر، قهوه و گوارش. نوشیدنی‌ها شامل نمی‌شود.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'اپریتیف، ۲ غذای انتخابی، دسر، قهوه و گوارش. نوشیدنی‌ها شامل نمی‌شود.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'یک غذای انتخابی + بستنی خانگی + نوشیدنی', 'Carta dei Vini': 'لیست شراب', 'Carta dei Vini Digitale': 'لیست دیجیتال شراب', 'Tocca per sfogliare': 'برای مرور لمس کنید', 'Vini, Champagne e Vino della Casa': 'شراب، شامپاین و شراب خانگی' },
    es: { '🥤 Bibite': '🥤 Bebidas', '🍺 Birre': '🍺 Cervezas', '🍸 Cocktail & Aperitivi': '🍸 Cócteles & Aperitivos', '☕ Caffetteria': '☕ Cafetería', '⭐ Consigliato': '⭐ Recomendado', 'Secondo disponibilità': 'Según disponibilidad', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Con tomate, mantequilla y salvia, champiñones o mantequilla y tomillo', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Con salsa de caza, champiñones o pesto fresco', 'Al Burro e Salvia o alle Noci': 'Con mantequilla y salvia o nueces', 'Al Pesto Fresco o Primavera': 'Con pesto fresco o primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Con champiñones, quesos y gorgonzola o mantequilla y salvia', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Con pimienta verde, gorgonzola o a la parrilla', 'Al Forno o alla Griglia — Secondo disponibilità': 'Al horno o a la parrilla — según disponibilidad', 'Dolce al caffè con mascarpone e cacao': 'Postre de café con mascarpone y cacao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Postre cremoso de vainilla con salsa de frutas', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Hecho en casa cada día — hasta 3 sabores a elegir', 'Disponibile con o senza alcol': 'Disponible con o sin alcohol', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Con nuestros platos típicos y la fórmula "todo incluido" (1 botella de vino de la casa cada 4 personas) — 5 platos seleccionados por la cocina', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitivo, 3 platos a elegir, postre, café y digestivo. Bebidas no incluidas.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitivo, 2 platos a elegir, postre, café y digestivo. Bebidas no incluidas.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Un plato a elegir + helado casero + bebida', 'Carta dei Vini': 'Carta de vinos', 'Carta dei Vini Digitale': 'Carta de vinos digital', 'Tocca per sfogliare': 'Toca para explorar', 'Vini, Champagne e Vino della Casa': 'Vinos, champán y vino de la casa' },
    pt: { '🥤 Bibite': '🥤 Bebidas', '🍺 Birre': '🍺 Cervejas', '🍸 Cocktail & Aperitivi': '🍸 Cocktails & Aperitivos', '☕ Caffetteria': '☕ Cafetaria', '⭐ Consigliato': '⭐ Recomendado', 'Secondo disponibilità': 'Consoante a disponibilidade', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Com tomate, manteiga e sálvia, cogumelos ou manteiga e tomilho', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Com molho de caça, cogumelos ou pesto fresco', 'Al Burro e Salvia o alle Noci': 'Com manteiga e sálvia ou nozes', 'Al Pesto Fresco o Primavera': 'Com pesto fresco ou primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Com cogumelos, queijos e gorgonzola ou manteiga e sálvia', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Com pimenta verde, gorgonzola ou grelhado', 'Al Forno o alla Griglia — Secondo disponibilità': 'No forno ou grelhado — consoante a disponibilidade', 'Dolce al caffè con mascarpone e cacao': 'Sobremesa de café com mascarpone e cacau', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Sobremesa cremosa de baunilha com molho de frutas', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Feito em casa todos os dias — até 3 sabores à escolha', 'Disponibile con o senza alcol': 'Disponível com ou sem álcool', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Com os nossos pratos típicos e a fórmula "tudo incluído" (1 garrafa de vinho da casa por cada 4 pessoas) — 5 pratos selecionados pela cozinha', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitivo, 3 pratos à escolha, sobremesa, café e digestivo. Bebidas não incluídas.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitivo, 2 pratos à escolha, sobremesa, café e digestivo. Bebidas não incluídas.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Um prato à escolha + gelado caseiro + bebida', 'Carta dei Vini': 'Carta de vinhos', 'Carta dei Vini Digitale': 'Carta de vinhos digital', 'Tocca per sfogliare': 'Toque para explorar', 'Vini, Champagne e Vino della Casa': 'Vinhos, champanhe e vinho da casa' },
    ru: { '🥤 Bibite': '🥤 Напитки', '🍺 Birre': '🍺 Пиво', '🍸 Cocktail & Aperitivi': '🍸 Коктейли & Аперитивы', '☕ Caffetteria': '☕ Кафе', '⭐ Consigliato': '⭐ Рекомендуем', 'Secondo disponibilità': 'В зависимости от наличия', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'С томатом, маслом и шалфеем, грибами или маслом и тимьяном', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'С соусом из дичи, грибами или свежим песто', 'Al Burro e Salvia o alle Noci': 'С маслом и шалфеем или грецкими орехами', 'Al Pesto Fresco o Primavera': 'Со свежим песто или примаверой', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'С грибами, сырами и горгонзолой или маслом и шалфеем', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'С зелёным перцем, горгонзолой или на гриле', 'Al Forno o alla Griglia — Secondo disponibilità': 'В духовке или на гриле — в зависимости от наличия', 'Dolce al caffè con mascarpone e cacao': 'Кофейный десерт с маскарпоне и какао', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Кремовый ванильный десерт с фруктовым соусом', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Домашнего приготовления каждый день — до 3 вкусов на выбор', 'Disponibile con o senza alcol': 'Доступно с алкоголем или без', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'С нашими традиционными блюдами и формулой "всё включено" (1 бутылка домашнего вина на 4 человек) — 5 блюд по выбору кухни', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 3 блюда на выбор, десерт, кофе и дижестив. Напитки не включены.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 2 блюда на выбор, десерт, кофе и дижестив. Напитки не включены.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Одно блюдо на выбор + домашнее мороженое + напиток', 'Carta dei Vini': 'Карта вин', 'Carta dei Vini Digitale': 'Цифровая карта вин', 'Tocca per sfogliare': 'Нажмите для просмотра', 'Vini, Champagne e Vino della Casa': 'Вина, шампанское и домашнее вино' },
    nl: { '🥤 Bibite': '🥤 Dranken', '🍺 Birre': '🍺 Bieren', '🍸 Cocktail & Aperitivi': '🍸 Cocktails & Aperitieven', '☕ Caffetteria': '☕ Café', '⭐ Consigliato': '⭐ Aanbevolen', 'Secondo disponibilità': 'Afhankelijk van beschikbaarheid', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Met tomaat, boter en salie, paddenstoelen of boter en tijm', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Met wildsaus, paddenstoelen of verse pesto', 'Al Burro e Salvia o alle Noci': 'Met boter en salie of walnoten', 'Al Pesto Fresco o Primavera': 'Met verse pesto of primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Met paddenstoelen, kazen en gorgonzola of boter en salie', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Met groene peper, gorgonzola of gegrild', 'Al Forno o alla Griglia — Secondo disponibilità': 'In de oven of gegrild — afhankelijk van beschikbaarheid', 'Dolce al caffè con mascarpone e cacao': 'Koffiedessert met mascarpone en cacao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Romig vanilledessert met fruitsaus', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Elke dag huisgemaakt — tot 3 smaken naar keuze', 'Disponibile con o senza alcol': 'Verkrijgbaar met of zonder alcohol', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Met onze typische gerechten en de "alles inbegrepen"-formule (1 fles huiswijn per 4 personen) — 5 door de keuken geselecteerde gangen', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitief, 3 gerechten naar keuze, dessert, koffie en digestief. Dranken niet inbegrepen.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitief, 2 gerechten naar keuze, dessert, koffie en digestief. Dranken niet inbegrepen.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Eén gerecht naar keuze + huisgemaakt ijs + drankje', 'Carta dei Vini': 'Wijnkaart', 'Carta dei Vini Digitale': 'Digitale wijnkaart', 'Tocca per sfogliare': 'Tik om te bladeren', 'Vini, Champagne e Vino della Casa': 'Wijnen, champagne en huiswijn' },
    pl: { '🥤 Bibite': '🥤 Napoje', '🍺 Birre': '🍺 Piwa', '🍸 Cocktail & Aperitivi': '🍸 Koktajle & Aperitify', '☕ Caffetteria': '☕ Kawiarnia', '⭐ Consigliato': '⭐ Polecane', 'Secondo disponibilità': 'W zależności od dostępności', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Z pomidorem, masłem i szałwią, grzybami lub masłem i tymiankiem', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Z sosem z dziczyzny, grzybami lub świeżym pesto', 'Al Burro e Salvia o alle Noci': 'Z masłem i szałwią lub orzechami włoskimi', 'Al Pesto Fresco o Primavera': 'Ze świeżym pesto lub primaverą', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Z grzybami, serami i gorgonzolą lub masłem i szałwią', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Z zielonym pieprzem, gorgonzolą lub z grilla', 'Al Forno o alla Griglia — Secondo disponibilità': 'Z piekarnika lub z grilla — w zależności od dostępności', 'Dolce al caffè con mascarpone e cacao': 'Deser kawowy z mascarpone i kakao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Kremowy deser waniliowy z sosem owocowym', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Domowej roboty codziennie — do 3 smaków do wyboru', 'Disponibile con o senza alcol': 'Dostępne z alkoholem lub bez', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Z naszymi typowymi daniami i formułą "wszystko w cenie" (1 butelka wina domowego na 4 osoby) — 5 dań wybranych przez kuchnię', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 3 dania do wyboru, deser, kawa i digestif. Napoje nie są wliczone.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 2 dania do wyboru, deser, kawa i digestif. Napoje nie są wliczone.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Jedno danie do wyboru + domowe lody + napój', 'Carta dei Vini': 'Karta win', 'Carta dei Vini Digitale': 'Cyfrowa karta win', 'Tocca per sfogliare': 'Dotknij, aby przeglądać', 'Vini, Champagne e Vino della Casa': 'Wina, szampan i wino domowe' },
    uk: { '🥤 Bibite': '🥤 Напої', '🍺 Birre': '🍺 Пиво', '🍸 Cocktail & Aperitivi': '🍸 Коктейлі & Аперитиви', '☕ Caffetteria': '☕ Кафе', '⭐ Consigliato': '⭐ Рекомендовано', 'Secondo disponibilità': 'Залежно від наявності', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'З томатом, маслом і шавлією, грибами або маслом і чебрецем', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Із соусом з дичини, грибами або свіжим песто', 'Al Burro e Salvia o alle Noci': 'З маслом і шавлією або волоськими горіхами', 'Al Pesto Fresco o Primavera': 'Зі свіжим песто або примаверою', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'З грибами, сирами та горгонзолою або маслом і шавлією', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Із зеленим перцем, горгонзолою або на грилі', 'Al Forno o alla Griglia — Secondo disponibilità': 'У духовці або на грилі — залежно від наявності', 'Dolce al caffè con mascarpone e cacao': 'Кавовий десерт з маскарпоне та какао', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Кремовий ванільний десерт із фруктовим соусом', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Домашнього приготування щодня — до 3 смаків на вибір', 'Disponibile con o senza alcol': 'Доступно з алкоголем або без', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'З нашими традиційними стравами та формулою "все включено" (1 пляшка домашнього вина на 4 особи) — 5 страв на вибір кухні', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 3 страви на вибір, десерт, кава та дижестив. Напої не включені.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Аперитив, 2 страви на вибір, десерт, кава та дижестив. Напої не включені.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Одна страва на вибір + домашнє морозиво + напій', 'Carta dei Vini': 'Карта вин', 'Carta dei Vini Digitale': 'Цифрова карта вин', 'Tocca per sfogliare': 'Торкніться, щоб переглянути', 'Vini, Champagne e Vino della Casa': 'Вина, шампанське та домашнє вино' },
    ro: { '🥤 Bibite': '🥤 Băuturi', '🍺 Birre': '🍺 Beri', '🍸 Cocktail & Aperitivi': '🍸 Cocktailuri & Aperitive', '☕ Caffetteria': '☕ Cafenea', '⭐ Consigliato': '⭐ Recomandat', 'Secondo disponibilità': 'În funcție de disponibilitate', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Cu roșii, unt și salvie, ciuperci sau unt și cimbru', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Cu sos de vânat, ciuperci sau pesto proaspăt', 'Al Burro e Salvia o alle Noci': 'Cu unt și salvie sau nuci', 'Al Pesto Fresco o Primavera': 'Cu pesto proaspăt sau primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Cu ciuperci, brânzeturi și gorgonzola sau unt și salvie', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Cu piper verde, gorgonzola sau la grătar', 'Al Forno o alla Griglia — Secondo disponibilità': 'La cuptor sau la grătar — în funcție de disponibilitate', 'Dolce al caffè con mascarpone e cacao': 'Desert de cafea cu mascarpone și cacao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Desert cremos de vanilie cu sos de fructe', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Preparat în casă zilnic — până la 3 arome la alegere', 'Disponibile con o senza alcol': 'Disponibil cu sau fără alcool', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Cu preparatele noastre tipice și formula "totul inclus" (1 sticlă de vin de casă la 4 persoane) — 5 feluri selectate de bucătărie', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 3 feluri la alegere, desert, cafea și digestiv. Băuturile nu sunt incluse.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 2 feluri la alegere, desert, cafea și digestiv. Băuturile nu sunt incluse.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Un fel la alegere + înghețată de casă + băutură', 'Carta dei Vini': 'Lista de vinuri', 'Carta dei Vini Digitale': 'Lista digitală de vinuri', 'Tocca per sfogliare': 'Atingeți pentru a răsfoi', 'Vini, Champagne e Vino della Casa': 'Vinuri, șampanie și vin de casă' },
    sv: { '🥤 Bibite': '🥤 Drycker', '🍺 Birre': '🍺 Öl', '🍸 Cocktail & Aperitivi': '🍸 Cocktails & Aperitif', '☕ Caffetteria': '☕ Café', '⭐ Consigliato': '⭐ Rekommenderas', 'Secondo disponibilità': 'Beroende på tillgänglighet', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Med tomat, smör och salvia, svamp eller smör och timjan', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Med viltsås, svamp eller färsk pesto', 'Al Burro e Salvia o alle Noci': 'Med smör och salvia eller valnötter', 'Al Pesto Fresco o Primavera': 'Med färsk pesto eller primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Med svamp, ostar och gorgonzola eller smör och salvia', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Med grön peppar, gorgonzola eller grillad', 'Al Forno o alla Griglia — Secondo disponibilità': 'Ugnsbakad eller grillad — beroende på tillgänglighet', 'Dolce al caffè con mascarpone e cacao': 'Kaffedessert med mascarpone och kakao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Krämig vaniljdessert med fruktsås', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Hemlagad varje dag — upp till 3 smaker att välja', 'Disponibile con o senza alcol': 'Finns med eller utan alkohol', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Med våra typiska rätter och "allt inkluderat"-formeln (1 flaska husets vin per 4 personer) — 5 rätter utvalda av köket', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 3 rätter att välja, dessert, kaffe och digestif. Dryck ingår ej.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 2 rätter att välja, dessert, kaffe och digestif. Dryck ingår ej.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'En rätt att välja + hemgjord glass + dryck', 'Carta dei Vini': 'Vinlista', 'Carta dei Vini Digitale': 'Digital vinlista', 'Tocca per sfogliare': 'Tryck för att bläddra', 'Vini, Champagne e Vino della Casa': 'Viner, champagne och husets vin' },
    da: { '🥤 Bibite': '🥤 Drikkevarer', '🍺 Birre': '🍺 Øl', '🍸 Cocktail & Aperitivi': '🍸 Cocktails & Aperitif', '☕ Caffetteria': '☕ Café', '⭐ Consigliato': '⭐ Anbefales', 'Secondo disponibilità': 'Afhængig af tilgængelighed', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Med tomat, smør og salvie, svampe eller smør og timian', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Med vildtsauce, svampe eller frisk pesto', 'Al Burro e Salvia o alle Noci': 'Med smør og salvie eller valnødder', 'Al Pesto Fresco o Primavera': 'Med frisk pesto eller primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Med svampe, oste og gorgonzola eller smør og salvie', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Med grøn peber, gorgonzola eller grillet', 'Al Forno o alla Griglia — Secondo disponibilità': 'Ovnbagt eller grillet — afhængig af tilgængelighed', 'Dolce al caffè con mascarpone e cacao': 'Kaffedessert med mascarpone og kakao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Cremet vaniljedessert med frugtsauce', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Hjemmelavet hver dag — op til 3 smage at vælge', 'Disponibile con o senza alcol': 'Fås med eller uden alkohol', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Med vores typiske retter og "alt inkluderet"-formlen (1 flaske husets vin pr. 4 personer) — 5 retter udvalgt af køkkenet', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 3 retter efter eget valg, dessert, kaffe og digestif. Drikkevarer er ikke inkluderet.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 2 retter efter eget valg, dessert, kaffe og digestif. Drikkevarer er ikke inkluderet.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'En ret efter eget valg + hjemmelavet is + drikkevare', 'Carta dei Vini': 'Vinkort', 'Carta dei Vini Digitale': 'Digitalt vinkort', 'Tocca per sfogliare': 'Tryk for at gennemse', 'Vini, Champagne e Vino della Casa': 'Vine, champagne og husets vin' },
    no: { '🥤 Bibite': '🥤 Drikke', '🍺 Birre': '🍺 Øl', '🍸 Cocktail & Aperitivi': '🍸 Cocktailer & Aperitiff', '☕ Caffetteria': '☕ Kafé', '⭐ Consigliato': '⭐ Anbefales', 'Secondo disponibilità': 'Avhengig av tilgjengelighet', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Med tomat, smør og salvie, sopp eller smør og timian', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Med viltsaus, sopp eller fersk pesto', 'Al Burro e Salvia o alle Noci': 'Med smør og salvie eller valnøtter', 'Al Pesto Fresco o Primavera': 'Med fersk pesto eller primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Med sopp, oster og gorgonzola eller smør og salvie', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Med grønn pepper, gorgonzola eller grillet', 'Al Forno o alla Griglia — Secondo disponibilità': 'Ovnsbakt eller grillet — avhengig av tilgjengelighet', 'Dolce al caffè con mascarpone e cacao': 'Kaffedessert med mascarpone og kakao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Kremet vaniljedessert med fruktsaus', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Hjemmelaget hver dag — inntil 3 smaker å velge', 'Disponibile con o senza alcol': 'Tilgjengelig med eller uten alkohol', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Med våre typiske retter og "alt inkludert"-formelen (1 flaske husets vin per 4 personer) — 5 retter valgt av kjøkkenet', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiff, 3 retter etter eget valg, dessert, kaffe og digestiff. Drikke er ikke inkludert.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiff, 2 retter etter eget valg, dessert, kaffe og digestiff. Drikke er ikke inkludert.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'En rett etter eget valg + hjemmelaget is + drikke', 'Carta dei Vini': 'Vinkart', 'Carta dei Vini Digitale': 'Digitalt vinkart', 'Tocca per sfogliare': 'Trykk for å bla', 'Vini, Champagne e Vino della Casa': 'Viner, champagne og husets vin' },
    fi: { '🥤 Bibite': '🥤 Juomat', '🍺 Birre': '🍺 Oluet', '🍸 Cocktail & Aperitivi': '🍸 Cocktailit & Aperitiivit', '☕ Caffetteria': '☕ Kahvila', '⭐ Consigliato': '⭐ Suositeltu', 'Secondo disponibilità': 'Saatavuuden mukaan', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Tomaatilla, voilla ja salvialla, sienillä tai voilla ja timjamilla', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Riistakastikkeella, sienillä tai tuoreella pestolla', 'Al Burro e Salvia o alle Noci': 'Voilla ja salvialla tai saksanpähkinöillä', 'Al Pesto Fresco o Primavera': 'Tuoreella pestolla tai primaveralla', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Sienillä, juustoilla ja gorgonzolalla tai voilla ja salvialla', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Vihreällä pippurilla, gorgonzolalla tai grillattuna', 'Al Forno o alla Griglia — Secondo disponibilità': 'Uunissa tai grillattuna — saatavuuden mukaan', 'Dolce al caffè con mascarpone e cacao': 'Kahvijälkiruoka mascarponella ja kaakaolla', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Kermainen vaniljajälkiruoka hedelmäkastikkeella', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Kotitekoista joka päivä — enintään 3 makua valittavana', 'Disponibile con o senza alcol': 'Saatavilla alkoholin kanssa tai ilman', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Tyypillisillä annoksillamme ja "kaikki mukana" -konseptilla (1 pullo talon viiniä 4 hengelle) — keittiön valitsemat 5 ruokalajia', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiivi, 3 valittavaa ruokalajia, jälkiruoka, kahvi ja digestiivi. Juomat eivät sisälly.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiivi, 2 valittavaa ruokalajia, jälkiruoka, kahvi ja digestiivi. Juomat eivät sisälly.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Yksi valittava ruokalaji + kotitekoinen jäätelö + juoma', 'Carta dei Vini': 'Viinilista', 'Carta dei Vini Digitale': 'Digitaalinen viinilista', 'Tocca per sfogliare': 'Napauta selataksesi', 'Vini, Champagne e Vino della Casa': 'Viinit, samppanja ja talon viini' },
    el: { '🥤 Bibite': '🥤 Αναψυκτικά', '🍺 Birre': '🍺 Μπύρες', '🍸 Cocktail & Aperitivi': '🍸 Κοκτέιλ & Απεριτίφ', '☕ Caffetteria': '☕ Καφετέρια', '⭐ Consigliato': '⭐ Προτεινόμενο', 'Secondo disponibilità': 'Ανάλογα με τη διαθεσιμότητα', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Με ντομάτα, βούτυρο και φασκόμηλο, μανιτάρια ή βούτυρο και θυμάρι', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Με σάλτσα κυνηγιού, μανιτάρια ή φρέσκο πέστο', 'Al Burro e Salvia o alle Noci': 'Με βούτυρο και φασκόμηλο ή καρύδια', 'Al Pesto Fresco o Primavera': 'Με φρέσκο πέστο ή primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Με μανιτάρια, τυριά και γκοργκοντζόλα ή βούτυρο και φασκόμηλο', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Με πράσινο πιπέρι, γκοργκοντζόλα ή στη σχάρα', 'Al Forno o alla Griglia — Secondo disponibilità': 'Στο φούρνο ή στη σχάρα — ανάλογα με τη διαθεσιμότητα', 'Dolce al caffè con mascarpone e cacao': 'Επιδόρπιο καφέ με μασκαρπόνε και κακάο', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Κρεμώδες επιδόρπιο βανίλιας με σάλτσα φρούτων', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Σπιτικό κάθε μέρα — έως 3 γεύσεις επιλογής', 'Disponibile con o senza alcol': 'Διαθέσιμο με ή χωρίς αλκοόλ', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Με τα παραδοσιακά μας πιάτα και τη φόρμουλα "όλα περιλαμβάνονται" (1 μπουκάλι κρασί σπιτιού ανά 4 άτομα) — 5 πιάτα επιλεγμένα από την κουζίνα', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Απεριτίφ, 3 πιάτα επιλογής, επιδόρπιο, καφές και χωνευτικό. Τα ποτά δεν περιλαμβάνονται.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Απεριτίφ, 2 πιάτα επιλογής, επιδόρπιο, καφές και χωνευτικό. Τα ποτά δεν περιλαμβάνονται.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Ένα πιάτο επιλογής + σπιτικό παγωτό + ποτό', 'Carta dei Vini': 'Κατάλογος κρασιών', 'Carta dei Vini Digitale': 'Ψηφιακός κατάλογος κρασιών', 'Tocca per sfogliare': 'Πατήστε για περιήγηση', 'Vini, Champagne e Vino della Casa': 'Κρασιά, σαμπάνια και κρασί σπιτιού' },
    cs: { '🥤 Bibite': '🥤 Nápoje', '🍺 Birre': '🍺 Piva', '🍸 Cocktail & Aperitivi': '🍸 Koktejly & Aperitivy', '☕ Caffetteria': '☕ Kavárna', '⭐ Consigliato': '⭐ Doporučeno', 'Secondo disponibilità': 'Dle dostupnosti', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'S rajčaty, máslem a šalvějí, houbami nebo máslem a tymiánem', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Se zvěřinovou omáčkou, houbami nebo čerstvým pestem', 'Al Burro e Salvia o alle Noci': 'S máslem a šalvějí nebo vlašskými ořechy', 'Al Pesto Fresco o Primavera': 'S čerstvým pestem nebo primaverou', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'S houbami, sýry a gorgonzolou nebo máslem a šalvějí', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Se zeleným pepřem, gorgonzolou nebo grilované', 'Al Forno o alla Griglia — Secondo disponibilità': 'Pečené nebo grilované — dle dostupnosti', 'Dolce al caffè con mascarpone e cacao': 'Kávový dezert s mascarpone a kakaem', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Krémový vanilkový dezert s ovocnou omáčkou', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Domácí výroba každý den — max. 3 příchutě na výběr', 'Disponibile con o senza alcol': 'K dispozici s alkoholem nebo bez', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'S našimi typickými jídly a formulí "vše v ceně" (1 láhev domácího vína na 4 osoby) — 5 chodů vybraných kuchyní', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 3 chody dle výběru, dezert, káva a digestiv. Nápoje nejsou zahrnuty.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitiv, 2 chody dle výběru, dezert, káva a digestiv. Nápoje nejsou zahrnuty.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Jeden chod dle výběru + domácí zmrzlina + nápoj', 'Carta dei Vini': 'Vinný lístek', 'Carta dei Vini Digitale': 'Digitální vinný lístek', 'Tocca per sfogliare': 'Klepnutím procházejte', 'Vini, Champagne e Vino della Casa': 'Vína, šampaňské a domácí víno' },
    hu: { '🥤 Bibite': '🥤 Üdítők', '🍺 Birre': '🍺 Sörök', '🍸 Cocktail & Aperitivi': '🍸 Koktélok & Aperitifek', '☕ Caffetteria': '☕ Kávézó', '⭐ Consigliato': '⭐ Ajánlott', 'Secondo disponibilità': 'Elérhetőség szerint', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Paradicsommal, vajjal és zsályával, gombával vagy vajjal és kakukkfűvel', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Vadszósszal, gombával vagy friss pestóval', 'Al Burro e Salvia o alle Noci': 'Vajjal és zsályával vagy dióval', 'Al Pesto Fresco o Primavera': 'Friss pestóval vagy primaverával', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Gombával, sajtokkal és gorgonzolával vagy vajjal és zsályával', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Zöldborssal, gorgonzolával vagy grillezve', 'Al Forno o alla Griglia — Secondo disponibilità': 'Sütőben vagy grillezve — elérhetőség szerint', 'Dolce al caffè con mascarpone e cacao': 'Kávés desszert mascarponéval és kakaóval', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Krémes vaníliás desszert gyümölcsszósszal', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Naponta házilag készítve — legfeljebb 3 íz választható', 'Disponibile con o senza alcol': 'Alkohollal vagy anélkül is elérhető', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Jellegzetes ételeinkkel és a "minden benne van" csomaggal (1 üveg házi bor 4 fő részére) — a konyha által válogatott 5 fogás', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 3 választható fogás, desszert, kávé és emésztést segítő ital. Az italok nem tartalmazottak.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Aperitif, 2 választható fogás, desszert, kávé és emésztést segítő ital. Az italok nem tartalmazottak.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Egy választható fogás + házi fagylalt + ital', 'Carta dei Vini': 'Borlap', 'Carta dei Vini Digitale': 'Digitális borlap', 'Tocca per sfogliare': 'Koppintson a böngészéshez', 'Vini, Champagne e Vino della Casa': 'Borok, pezsgő és házi bor' },
    vi: { '🥤 Bibite': '🥤 Đồ Uống', '🍺 Birre': '🍺 Bia', '🍸 Cocktail & Aperitivi': '🍸 Cocktail & Khai Vị', '☕ Caffetteria': '☕ Quán Cà Phê', '⭐ Consigliato': '⭐ Đề Xuất', 'Secondo disponibilità': 'Tùy theo tình trạng có sẵn', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'Với cà chua, bơ và xô thơm, nấm hoặc bơ và cỏ xạ hương', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'Với sốt thịt thú rừng, nấm hoặc pesto tươi', 'Al Burro e Salvia o alle Noci': 'Với bơ và xô thơm hoặc quả óc chó', 'Al Pesto Fresco o Primavera': 'Với pesto tươi hoặc primavera', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'Với nấm, phô mai và gorgonzola hoặc bơ và xô thơm', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'Với tiêu xanh, gorgonzola hoặc nướng', 'Al Forno o alla Griglia — Secondo disponibilità': 'Nướng lò hoặc nướng vỉ — tùy theo tình trạng có sẵn', 'Dolce al caffè con mascarpone e cacao': 'Món tráng miệng cà phê với mascarpone và ca cao', 'Dolce cremoso alla vaniglia con salsa di frutta': 'Món tráng miệng vani kem béo với sốt trái cây', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'Làm tại nhà mỗi ngày — chọn tối đa 3 vị', 'Disponibile con o senza alcol': 'Có sẵn có hoặc không có cồn', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'Với các món ăn đặc trưng của chúng tôi và gói "trọn gói" (1 chai rượu nhà cho mỗi 4 người) — 5 món do bếp lựa chọn', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Khai vị, 3 món tự chọn, tráng miệng, cà phê và rượu tiêu hóa. Không bao gồm đồ uống.', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'Khai vị, 2 món tự chọn, tráng miệng, cà phê và rượu tiêu hóa. Không bao gồm đồ uống.', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'Một món tự chọn + kem tự làm + đồ uống', 'Carta dei Vini': 'Danh sách rượu vang', 'Carta dei Vini Digitale': 'Danh sách rượu vang kỹ thuật số', 'Tocca per sfogliare': 'Chạm để xem', 'Vini, Champagne e Vino della Casa': 'Rượu vang, champagne và rượu vang nhà' },
    th: { '🥤 Bibite': '🥤 เครื่องดื่ม', '🍺 Birre': '🍺 เบียร์', '🍸 Cocktail & Aperitivi': '🍸 ค็อกเทล & อาเปอริทีฟ', '☕ Caffetteria': '☕ คาเฟ่', '⭐ Consigliato': '⭐ แนะนำ', 'Secondo disponibilità': 'ขึ้นอยู่กับความพร้อม', 'Al Pomodoro, Burro e Salvia, Funghi o Burro e Timo': 'กับมะเขือเทศ เนยและเสจ เห็ด หรือเนยและไธม์', 'Alla Selvaggina, ai Funghi o al Pesto Fresco': 'กับซอสเนื้อสัตว์ป่า เห็ด หรือเปสโตสด', 'Al Burro e Salvia o alle Noci': 'กับเนยและเสจ หรือวอลนัท', 'Al Pesto Fresco o Primavera': 'กับเปสโตสด หรือผักฤดูใบไม้ผลิ', 'Ai Funghi, ai Formaggi con Gorgonzola o Burro e Salvia': 'กับเห็ด ชีสและกอร์กอนโซล่า หรือเนยและเสจ', 'Al Pepe Verde, al Gorgonzola o alla Griglia': 'กับพริกไทยเขียว กอร์กอนโซล่า หรือย่าง', 'Al Forno o alla Griglia — Secondo disponibilità': 'อบหรือย่าง — ขึ้นอยู่กับความพร้อม', 'Dolce al caffè con mascarpone e cacao': 'ของหวานกาแฟกับมาสคาร์โปเน่และโกโก้', 'Dolce cremoso alla vaniglia con salsa di frutta': 'ของหวานวานิลลาครีมกับซอสผลไม้', 'Fatto in Casa ogni Giorno — max 3 gusti a scelta': 'ทำเองทุกวัน — เลือกได้สูงสุด 3 รสชาติ', 'Disponibile con o senza alcol': 'มีทั้งแบบมีแอลกอฮอล์และไม่มี', 'Con i nostri Piatti Tipici e la Formula "Tutto Compreso" (1 bott. Vino della Casa ogni 4 pers.) — 5 Portate Selezionate dalla Cucina': 'พร้อมอาหารขึ้นชื่อของเราและแพ็กเกจ "รวมทุกอย่าง" (ไวน์บ้าน 1 ขวดต่อ 4 ท่าน) — 5 เมนูที่คัดสรรโดยครัว', 'Aperitivo, 3 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'อาเปอริทีฟ เลือก 3 เมนู ของหวาน กาแฟ และไดเจสทีฟ ไม่รวมเครื่องดื่ม', 'Aperitivo, 2 Portate a scelta, Dessert, Caffè e Digestivo. Bevande Escluse.': 'อาเปอริทีฟ เลือก 2 เมนู ของหวาน กาแฟ และไดเจสทีฟ ไม่รวมเครื่องดื่ม', 'Un Piatto a scelta + Gelato Fatto in Casa + Bibita': 'เลือก 1 เมนู + ไอศกรีมทำเอง + เครื่องดื่ม', 'Carta dei Vini': 'รายการไวน์', 'Carta dei Vini Digitale': 'รายการไวน์ดิจิทัล', 'Tocca per sfogliare': 'แตะเพื่อเรียกดู', 'Vini, Champagne e Vino della Casa': 'ไวน์ แชมเปญ และไวน์บ้าน' }
  };

  Object.keys(MISC_ADD).forEach(function (lang) {
    if (!window.I18N_PATCH[lang]) window.I18N_PATCH[lang] = {};
    if (!window.I18N_PATCH[lang].misc) window.I18N_PATCH[lang].misc = {};
    Object.keys(MISC_ADD[lang]).forEach(function (key) {
      window.I18N_PATCH[lang].misc[key] = MISC_ADD[lang][key];
    });
  });

  var langsFixed = 0, sauceCount = 0, noteCount = 0, warnCount = 0;

  Object.keys(SAUCE_ADD).forEach(function (lang) {
    if (!window.I18N_PATCH[lang]) window.I18N_PATCH[lang] = {};
    if (!window.I18N_PATCH[lang].sauces) window.I18N_PATCH[lang].sauces = {};
    Object.keys(SAUCE_ADD[lang]).forEach(function (key) {
      window.I18N_PATCH[lang].sauces[key] = SAUCE_ADD[lang][key];
      sauceCount++;
    });
  });

  Object.keys(NOTE_ADD).forEach(function (lang) {
    if (!window.I18N_PATCH[lang]) window.I18N_PATCH[lang] = {};
    window.I18N_PATCH[lang].nota_label = NOTE_ADD[lang].nota_label;
    window.I18N_PATCH[lang].nota_ph = NOTE_ADD[lang].nota_ph;
    noteCount++;
  });

  Object.keys(DEGU_WARN_FIX).forEach(function (lang) {
    if (!window.I18N_PATCH[lang]) window.I18N_PATCH[lang] = {};
    window.I18N_PATCH[lang].pkg_degu_warn = DEGU_WARN_FIX[lang];
    warnCount++;
  });


  // 5) Custom alert/confirm popup messages (order sent, table required,
  //    no beverage, offline, error, clear cart, added-to-cart toast, etc.)
  //    These are read via the menu's tMsg() helper for any language beyond
  //    the 4 core ones, falling back straight into this pack's top level.
  var MSG_ADD = {
    'tr': { msg_added_cart: '✓ Sepete eklendi', msg_clear_cart_q: 'Sepeti boşalt?', msg_clear_yes: '✓ Evet, boşalt', msg_cancel: 'İptal', msg_items_word: 'ürün', msg_note_title: '📝 Not', msg_table_occupied: 'ℹ️ Bu masa dolu görünüyor — eğer orada oturuyorsanız sorun yok.', msg_offline: '📡 İnternet bağlantısı yok. Tekrar çevrimiçi olduğunuzda deneyin.', msg_table_required: '⚠️ Göndermeden önce masa numaranızı seçin!', msg_no_beverage: '⚠️ Herhangi bir içecek eklemediniz. Yine de siparişi göndermek istiyor musunuz?', msg_send_anyway: '✓ Evet, yine de gönder', msg_go_back: 'Geri dön', msg_order_sent: 'Sipariş başarıyla gönderildi! Garson kısa süre içinde alacak.', msg_modal_ok: '✓ Anladım', msg_order_error: '❌ Gönderim sırasında hata oluştu. Tekrar deneyin.' },
    'bg': { msg_added_cart: '✓ Добавено в количката', msg_clear_cart_q: 'Да изпразня ли количката?', msg_clear_yes: '✓ Да, изпразни', msg_cancel: 'Отказ', msg_items_word: 'артикула', msg_note_title: '📝 Забележка', msg_table_occupied: 'ℹ️ Тази маса изглежда вече заета — ако сте вие, всичко е наред.', msg_offline: '📡 Няма интернет връзка. Опитайте отново, когато сте онлайн.', msg_table_required: '⚠️ Изберете номер на маса преди да изпратите!', msg_no_beverage: '⚠️ Не сте добавили напитка. Искате ли все пак да изпратите поръчката?', msg_send_anyway: '✓ Да, изпрати въпреки това', msg_go_back: 'Назад', msg_order_sent: 'Поръчката е изпратена успешно! Сервитьорът ще я получи скоро.', msg_modal_ok: '✓ Разбрах', msg_order_error: '❌ Грешка при изпращането. Опитайте отново.' },
    'sk': { msg_added_cart: '✓ Pridané do košíka', msg_clear_cart_q: 'Vyprázdniť košík?', msg_clear_yes: '✓ Áno, vyprázdniť', msg_cancel: 'Zrušiť', msg_items_word: 'položiek', msg_note_title: '📝 Poznámka', msg_table_occupied: 'ℹ️ Tento stôl sa zdá byť obsadený — ak ste to vy, všetko je v poriadku.', msg_offline: '📡 Žiadne internetové pripojenie. Skúste to znova, keď budete online.', msg_table_required: '⚠️ Pred odoslaním vyberte číslo stola!', msg_no_beverage: '⚠️ Nepridali ste žiadny nápoj. Chcete napriek tomu odoslať objednávku?', msg_send_anyway: '✓ Áno, odoslať napriek tomu', msg_go_back: 'Späť', msg_order_sent: 'Objednávka bola úspešne odoslaná! Čašník ju čoskoro dostane.', msg_modal_ok: '✓ Rozumiem', msg_order_error: '❌ Chyba pri odosielaní. Skúste to znova.' },
    'hr': { msg_added_cart: '✓ Dodano u košaricu', msg_clear_cart_q: 'Isprazniti košaricu?', msg_clear_yes: '✓ Da, isprazni', msg_cancel: 'Odustani', msg_items_word: 'stavki', msg_note_title: '📝 Napomena', msg_table_occupied: 'ℹ️ Čini se da je ovaj stol već zauzet — ako ste to vi, sve je u redu.', msg_offline: '📡 Nema internetske veze. Pokušajte ponovno kada budete online.', msg_table_required: '⚠️ Odaberite broj stola prije slanja!', msg_no_beverage: '⚠️ Niste dodali piće. Želite li ipak poslati narudžbu?', msg_send_anyway: '✓ Da, ipak pošalji', msg_go_back: 'Natrag', msg_order_sent: 'Narudžba je uspješno poslana! Konobar će je uskoro primiti.', msg_modal_ok: '✓ Razumijem', msg_order_error: '❌ Greška prilikom slanja. Pokušajte ponovno.' },
    'sr': { msg_added_cart: '✓ Додато у корпу', msg_clear_cart_q: 'Испразнити корпу?', msg_clear_yes: '✓ Да, испразни', msg_cancel: 'Откажи', msg_items_word: 'ставки', msg_note_title: '📝 Напомена', msg_table_occupied: 'ℹ️ Овај сто изгледа већ заузет — ако сте то ви, све је у реду.', msg_offline: '📡 Нема интернет везе. Покушајте поново када будете онлајн.', msg_table_required: '⚠️ Изаберите број стола пре слања!', msg_no_beverage: '⚠️ Нисте додали пиће. Желите ли ипак да пошаљете наруџбину?', msg_send_anyway: '✓ Да, ипак пошаљи', msg_go_back: 'Назад', msg_order_sent: 'Наруџбина је успешно послата! Конобар ће је ускоро примити.', msg_modal_ok: '✓ Разумем', msg_order_error: '❌ Грешка при слању. Покушајте поново.' },
    'sl': { msg_added_cart: '✓ Dodano v košarico', msg_clear_cart_q: 'Izprazniti košarico?', msg_clear_yes: '✓ Da, izprazni', msg_cancel: 'Prekliči', msg_items_word: 'artiklov', msg_note_title: '📝 Opomba', msg_table_occupied: 'ℹ️ Ta miza je videti že zasedena — če ste to vi, je vse v redu.', msg_offline: '📡 Ni internetne povezave. Poskusite znova, ko boste spet povezani.', msg_table_required: '⚠️ Pred pošiljanjem izberite številko mize!', msg_no_beverage: '⚠️ Niste dodali pijače. Ali želite kljub temu poslati naročilo?', msg_send_anyway: '✓ Da, vseeno pošlji', msg_go_back: 'Nazaj', msg_order_sent: 'Naročilo je bilo uspešno poslano! Natakar ga bo kmalu prejel.', msg_modal_ok: '✓ Razumem', msg_order_error: '❌ Napaka pri pošiljanju. Poskusite znova.' },
    'ar': { msg_added_cart: '✓ تمت الإضافة إلى السلة', msg_clear_cart_q: 'إفراغ السلة؟', msg_clear_yes: '✓ نعم، أفرغ', msg_cancel: 'إلغاء', msg_items_word: 'عناصر', msg_note_title: '📝 ملاحظة', msg_table_occupied: 'ℹ️ تبدو هذه الطاولة مشغولة بالفعل — إذا كنت أنت الجالس هنا، فلا مشكلة.', msg_offline: '📡 لا يوجد اتصال بالإنترنت. حاول مرة أخرى عند العودة للاتصال.', msg_table_required: '⚠️ يرجى اختيار رقم الطاولة قبل الإرسال!', msg_no_beverage: '⚠️ لم تقم بإضافة أي مشروب. هل تريد إرسال الطلب على أي حال؟', msg_send_anyway: '✓ نعم، أرسل على أي حال', msg_go_back: 'رجوع', msg_order_sent: 'تم إرسال الطلب بنجاح! سيستلمه النادل قريبًا.', msg_modal_ok: '✓ فهمت', msg_order_error: '❌ حدث خطأ أثناء الإرسال. حاول مرة أخرى.' },
    'zh-CN': { msg_added_cart: '✓ 已加入购物车', msg_clear_cart_q: '清空购物车？', msg_clear_yes: '✓ 是的，清空', msg_cancel: '取消', msg_items_word: '项', msg_note_title: '📝 备注', msg_table_occupied: 'ℹ️ 此桌似乎已被占用——如果是您坐在这里，没有问题。', msg_offline: '📡 没有网络连接。重新联网后请再试一次。', msg_table_required: '⚠️ 发送前请先选择桌号！', msg_no_beverage: '⚠️ 您还没有添加饮品。仍要发送订单吗？', msg_send_anyway: '✓ 是的，仍然发送', msg_go_back: '返回', msg_order_sent: '订单发送成功！服务员很快会收到。', msg_modal_ok: '✓ 知道了', msg_order_error: '❌ 发送时出错，请重试。' },
    'ja': { msg_added_cart: '✓ カートに追加しました', msg_clear_cart_q: 'カートを空にしますか？', msg_clear_yes: '✓ はい、空にする', msg_cancel: 'キャンセル', msg_items_word: '点', msg_note_title: '📝 メモ', msg_table_occupied: 'ℹ️ このテーブルはすでに使用中のようです — ご本人であれば問題ありません。', msg_offline: '📡 インターネット接続がありません。オンラインに戻ってから再試行してください。', msg_table_required: '⚠️ 送信前にテーブル番号を選択してください！', msg_no_beverage: '⚠️ 飲み物が追加されていません。それでも注文を送信しますか？', msg_send_anyway: '✓ はい、それでも送信する', msg_go_back: '戻る', msg_order_sent: 'ご注文が送信されました！スタッフがまもなく確認します。', msg_modal_ok: '✓ 了解', msg_order_error: '❌ 送信中にエラーが発生しました。もう一度お試しください。' },
    'ko': { msg_added_cart: '✓ 장바구니에 추가됨', msg_clear_cart_q: '장바구니를 비우시겠습니까?', msg_clear_yes: '✓ 예, 비우기', msg_cancel: '취소', msg_items_word: '개', msg_note_title: '📝 메모', msg_table_occupied: 'ℹ️ 이 테이블은 이미 사용 중인 것 같습니다 — 본인이라면 문제 없습니다.', msg_offline: '📡 인터넷 연결이 없습니다. 다시 온라인 상태가 되면 시도해 주세요.', msg_table_required: '⚠️ 전송하기 전에 테이블 번호를 선택하세요!', msg_no_beverage: '⚠️ 음료를 추가하지 않았습니다. 그래도 주문을 보내시겠습니까?', msg_send_anyway: '✓ 예, 그래도 보내기', msg_go_back: '뒤로', msg_order_sent: '주문이 성공적으로 전송되었습니다! 곧 직원이 확인합니다.', msg_modal_ok: '✓ 확인', msg_order_error: '❌ 전송 중 오류가 발생했습니다. 다시 시도하세요.' },
    'hi': { msg_added_cart: '✓ कार्ट में जोड़ा गया', msg_clear_cart_q: 'कार्ट खाली करें?', msg_clear_yes: '✓ हां, खाली करें', msg_cancel: 'रद्द करें', msg_items_word: 'आइटम', msg_note_title: '📝 नोट', msg_table_occupied: 'ℹ️ यह टेबल पहले से ही व्याप्त दिख रही है — अगर आप वहीं बैठे हैं तो कोई समस्या नहीं।', msg_offline: '📡 इंटरनेट कनेक्शन नहीं है। ऑनलाइन होने पर पुनः प्रयास करें।', msg_table_required: '⚠️ भेजने से पहले टेबल नंबर चुनें!', msg_no_beverage: '⚠️ आपने कोई पेय नहीं जोड़ा। क्या फिर भी ऑर्डर भेजना चाहते हैं?', msg_send_anyway: '✓ हां, फिर भी भेजें', msg_go_back: 'वापस जाएं', msg_order_sent: 'ऑर्डर सफलतापूर्वक भेजा गया! वेटर जल्द ही प्राप्त करेगा।', msg_modal_ok: '✓ समझ गया', msg_order_error: '❌ भेजने में त्रुटि हुई। पुनः प्रयास करें।' },
    'bn': { msg_added_cart: '✓ কার্টে যোগ হয়েছে', msg_clear_cart_q: 'কার্ট খালি করবেন?', msg_clear_yes: '✓ হ্যাঁ, খালি করুন', msg_cancel: 'বাতিল', msg_items_word: 'আইটেম', msg_note_title: '📝 নোট', msg_table_occupied: 'ℹ️ এই টেবিলটি ইতিমধ্যে ব্যবহৃত মনে হচ্ছে — যদি আপনি এখানে বসে থাকেন, তাহলে কোনো সমস্যা নেই।', msg_offline: '📡 কোনো ইন্টারনেট সংযোগ নেই। আবার অনলাইনে এলে চেষ্টা করুন।', msg_table_required: '⚠️ পাঠানোর আগে টেবিল নম্বর নির্বাচন করুন!', msg_no_beverage: '⚠️ আপনি কোনো পানীয় যোগ করেননি। তবুও অর্ডার পাঠাতে চান?', msg_send_anyway: '✓ হ্যাঁ, তবুও পাঠান', msg_go_back: 'ফিরে যান', msg_order_sent: 'অর্ডার সফলভাবে পাঠানো হয়েছে! ওয়েটার শীঘ্রই পাবেন।', msg_modal_ok: '✓ বুঝেছি', msg_order_error: '❌ পাঠাতে ত্রুটি হয়েছে। আবার চেষ্টা করুন।' },
    'ur': { msg_added_cart: '✓ کارٹ میں شامل کر دیا گیا', msg_clear_cart_q: 'کارٹ خالی کریں؟', msg_clear_yes: '✓ ہاں، خالی کریں', msg_cancel: 'منسوخ کریں', msg_items_word: 'اشیاء', msg_note_title: '📝 نوٹ', msg_table_occupied: 'ℹ️ یہ میز پہلے سے مصروف دکھائی دے رہی ہے — اگر آپ یہاں بیٹھے ہیں تو کوئی مسئلہ نہیں۔', msg_offline: '📡 انٹرنیٹ کنکشن نہیں ہے۔ دوبارہ آن لائن ہونے پر کوشش کریں۔', msg_table_required: '⚠️ بھیجنے سے پہلے میز نمبر منتخب کریں!', msg_no_beverage: '⚠️ آپ نے کوئی مشروب شامل نہیں کیا۔ کیا آپ پھر بھی آرڈر بھیجنا چاہتے ہیں؟', msg_send_anyway: '✓ ہاں، پھر بھی بھیجیں', msg_go_back: 'واپس جائیں', msg_order_sent: 'آرڈر کامیابی سے بھیج دیا گیا! ویٹر جلد ہی وصول کرے گا۔', msg_modal_ok: '✓ سمجھ گیا', msg_order_error: '❌ بھیجنے میں خرابی ہوئی۔ دوبارہ کوشش کریں۔' },
    'fa': { msg_added_cart: '✓ به سبد خرید اضافه شد', msg_clear_cart_q: 'سبد خرید خالی شود؟', msg_clear_yes: '✓ بله، خالی کن', msg_cancel: 'لغو', msg_items_word: 'مورد', msg_note_title: '📝 یادداشت', msg_table_occupied: 'ℹ️ به نظر می‌رسد این میز قبلاً اشغال شده — اگر شما آنجا نشسته‌اید مشکلی نیست.', msg_offline: '📡 اتصال اینترنت وجود ندارد. پس از اتصال دوباره تلاش کنید.', msg_table_required: '⚠️ لطفاً قبل از ارسال شماره میز را انتخاب کنید!', msg_no_beverage: '⚠️ نوشیدنی‌ای اضافه نکرده‌اید. آیا با این حال می‌خواهید سفارش را ارسال کنید؟', msg_send_anyway: '✓ بله، به هر حال ارسال کن', msg_go_back: 'بازگشت', msg_order_sent: 'سفارش با موفقیت ارسال شد! گارسون به‌زودی آن را دریافت می‌کند.', msg_modal_ok: '✓ متوجه شدم', msg_order_error: '❌ خطا در ارسال. دوباره تلاش کنید.' },
    'es': { msg_added_cart: '✓ Añadido al carrito', msg_clear_cart_q: '¿Vaciar el carrito?', msg_clear_yes: '✓ Sí, vaciar', msg_cancel: 'Cancelar', msg_items_word: 'artículos', msg_note_title: '📝 Nota', msg_table_occupied: 'ℹ️ Esta mesa parece estar ya ocupada — si eres tú quien está sentado aquí, no hay problema.', msg_offline: '📡 Sin conexión a internet. Vuelve a intentarlo cuando estés en línea.', msg_table_required: '⚠️ ¡Selecciona el número de mesa antes de enviar!', msg_no_beverage: '⚠️ No has añadido ninguna bebida. ¿Quieres enviar el pedido de todos modos?', msg_send_anyway: '✓ Sí, enviar de todos modos', msg_go_back: 'Volver', msg_order_sent: '¡Pedido enviado con éxito! El camarero lo recibirá en breve.', msg_modal_ok: '✓ Entendido', msg_order_error: '❌ Error al enviar. Inténtalo de nuevo.' },
    'pt': { msg_added_cart: '✓ Adicionado ao carrinho', msg_clear_cart_q: 'Esvaziar o carrinho?', msg_clear_yes: '✓ Sim, esvaziar', msg_cancel: 'Cancelar', msg_items_word: 'itens', msg_note_title: '📝 Nota', msg_table_occupied: 'ℹ️ Esta mesa já parece estar ocupada — se for você que está aqui, tudo bem.', msg_offline: '📡 Sem conexão à internet. Tente novamente quando estiver online.', msg_table_required: '⚠️ Selecione o número da mesa antes de enviar!', msg_no_beverage: '⚠️ Não adicionou nenhuma bebida. Deseja enviar o pedido mesmo assim?', msg_send_anyway: '✓ Sim, enviar mesmo assim', msg_go_back: 'Voltar', msg_order_sent: 'Pedido enviado com sucesso! O garçom irá recebê-lo em breve.', msg_modal_ok: '✓ Entendi', msg_order_error: '❌ Erro ao enviar. Tente novamente.' },
    'ru': { msg_added_cart: '✓ Добавлено в корзину', msg_clear_cart_q: 'Очистить корзину?', msg_clear_yes: '✓ Да, очистить', msg_cancel: 'Отмена', msg_items_word: 'позиций', msg_note_title: '📝 Примечание', msg_table_occupied: 'ℹ️ Этот стол уже занят — если это вы здесь сидите, всё в порядке.', msg_offline: '📡 Нет подключения к интернету. Повторите попытку, когда снова будете онлайн.', msg_table_required: '⚠️ Выберите номер стола перед отправкой!', msg_no_beverage: '⚠️ Вы не добавили напитки. Всё равно отправить заказ?', msg_send_anyway: '✓ Да, всё равно отправить', msg_go_back: 'Назад', msg_order_sent: 'Заказ успешно отправлен! Официант скоро его получит.', msg_modal_ok: '✓ Понятно', msg_order_error: '❌ Ошибка при отправке. Попробуйте снова.' },
    'nl': { msg_added_cart: '✓ Toegevoegd aan winkelwagen', msg_clear_cart_q: 'Winkelwagen leegmaken?', msg_clear_yes: '✓ Ja, leegmaken', msg_cancel: 'Annuleren', msg_items_word: 'items', msg_note_title: '📝 Notitie', msg_table_occupied: 'ℹ️ Deze tafel lijkt al bezet — als u hier zit, is dat geen probleem.', msg_offline: '📡 Geen internetverbinding. Probeer het opnieuw zodra u weer online bent.', msg_table_required: '⚠️ Selecteer eerst uw tafelnummer voordat u verzendt!', msg_no_beverage: '⚠️ U heeft geen drankje toegevoegd. Wilt u de bestelling toch verzenden?', msg_send_anyway: '✓ Ja, toch verzenden', msg_go_back: 'Terug', msg_order_sent: 'Bestelling succesvol verzonden! De ober ontvangt deze binnenkort.', msg_modal_ok: '✓ Begrepen', msg_order_error: '❌ Fout bij het verzenden. Probeer het opnieuw.' },
    'pl': { msg_added_cart: '✓ Dodano do koszyka', msg_clear_cart_q: 'Opróżnić koszyk?', msg_clear_yes: '✓ Tak, opróżnij', msg_cancel: 'Anuluj', msg_items_word: 'pozycji', msg_note_title: '📝 Notatka', msg_table_occupied: 'ℹ️ Ten stolik wydaje się już zajęty — jeśli to Ty tu siedzisz, wszystko w porządku.', msg_offline: '📡 Brak połączenia z internetem. Spróbuj ponownie, gdy będziesz online.', msg_table_required: '⚠️ Wybierz numer stolika przed wysłaniem!', msg_no_beverage: '⚠️ Nie dodałeś żadnego napoju. Czy mimo to wysłać zamówienie?', msg_send_anyway: '✓ Tak, wyślij mimo to', msg_go_back: 'Wstecz', msg_order_sent: 'Zamówienie zostało pomyślnie wysłane! Kelner wkrótce je otrzyma.', msg_modal_ok: '✓ Rozumiem', msg_order_error: '❌ Błąd podczas wysyłania. Spróbuj ponownie.' },
    'uk': { msg_added_cart: '✓ Додано в кошик', msg_clear_cart_q: 'Очистити кошик?', msg_clear_yes: '✓ Так, очистити', msg_cancel: 'Скасувати', msg_items_word: 'позицій', msg_note_title: '📝 Примітка', msg_table_occupied: 'ℹ️ Цей стіл вже здається зайнятим — якщо це ви тут сидите, все гаразд.', msg_offline: '📡 Немає підключення до інтернету. Спробуйте знову, коли будете онлайн.', msg_table_required: '⚠️ Виберіть номер столу перед відправкою!', msg_no_beverage: '⚠️ Ви не додали напій. Все одно надіслати замовлення?', msg_send_anyway: '✓ Так, все одно надіслати', msg_go_back: 'Назад', msg_order_sent: 'Замовлення успішно надіслано! Офіціант скоро його отримає.', msg_modal_ok: '✓ Зрозуміло', msg_order_error: '❌ Помилка під час надсилання. Спробуйте ще раз.' },
    'ro': { msg_added_cart: '✓ Adăugat în coș', msg_clear_cart_q: 'Goliți coșul?', msg_clear_yes: '✓ Da, golește', msg_cancel: 'Anulează', msg_items_word: 'articole', msg_note_title: '📝 Notă', msg_table_occupied: 'ℹ️ Această masă pare deja ocupată — dacă sunteți dvs. aici, nu e nicio problemă.', msg_offline: '📡 Nu există conexiune la internet. Încercați din nou când reveniți online.', msg_table_required: '⚠️ Selectați numărul mesei înainte de a trimite!', msg_no_beverage: '⚠️ Nu ați adăugat nicio băutură. Doriți totuși să trimiteți comanda?', msg_send_anyway: '✓ Da, trimite oricum', msg_go_back: 'Înapoi', msg_order_sent: 'Comanda a fost trimisă cu succes! Chelnerul o va primi în curând.', msg_modal_ok: '✓ Am înțeles', msg_order_error: '❌ Eroare la trimitere. Încercați din nou.' },
    'sv': { msg_added_cart: '✓ Tillagd i varukorgen', msg_clear_cart_q: 'Töm varukorgen?', msg_clear_yes: '✓ Ja, töm', msg_cancel: 'Avbryt', msg_items_word: 'artiklar', msg_note_title: '📝 Anteckning', msg_table_occupied: 'ℹ️ Det här bordet verkar redan vara upptaget — om det är du som sitter här är allt bra.', msg_offline: '📡 Ingen internetanslutning. Försök igen när du är online.', msg_table_required: '⚠️ Välj bordsnummer innan du skickar!', msg_no_beverage: '⚠️ Du har inte lagt till någon dryck. Vill du skicka beställningen ändå?', msg_send_anyway: '✓ Ja, skicka ändå', msg_go_back: 'Tillbaka', msg_order_sent: 'Beställningen har skickats! Servitören tar emot den inom kort.', msg_modal_ok: '✓ Uppfattat', msg_order_error: '❌ Fel vid skickning. Försök igen.' },
    'da': { msg_added_cart: '✓ Tilføjet til kurven', msg_clear_cart_q: 'Tøm kurven?', msg_clear_yes: '✓ Ja, tøm', msg_cancel: 'Annuller', msg_items_word: 'varer', msg_note_title: '📝 Note', msg_table_occupied: 'ℹ️ Dette bord ser allerede optaget ud — hvis det er dig, der sidder her, er alt fint.', msg_offline: '📡 Ingen internetforbindelse. Prøv igen, når du er online igen.', msg_table_required: '⚠️ Vælg bordnummer, før du sender!', msg_no_beverage: '⚠️ Du har ikke tilføjet nogen drikkevarer. Vil du sende bestillingen alligevel?', msg_send_anyway: '✓ Ja, send alligevel', msg_go_back: 'Tilbage', msg_order_sent: 'Bestillingen blev sendt! Tjeneren modtager den snart.', msg_modal_ok: '✓ Forstået', msg_order_error: '❌ Fejl under afsendelse. Prøv igen.' },
    'no': { msg_added_cart: '✓ Lagt til i handlekurven', msg_clear_cart_q: 'Tøm handlekurven?', msg_clear_yes: '✓ Ja, tøm', msg_cancel: 'Avbryt', msg_items_word: 'varer', msg_note_title: '📝 Notat', msg_table_occupied: 'ℹ️ Dette bordet ser allerede opptatt ut — hvis det er deg som sitter her, er alt greit.', msg_offline: '📡 Ingen internettforbindelse. Prøv igjen når du er online igjen.', msg_table_required: '⚠️ Velg bordnummer før du sender!', msg_no_beverage: '⚠️ Du har ikke lagt til noen drikke. Vil du sende bestillingen likevel?', msg_send_anyway: '✓ Ja, send likevel', msg_go_back: 'Tilbake', msg_order_sent: 'Bestillingen ble sendt! Kelneren mottar den snart.', msg_modal_ok: '✓ Forstått', msg_order_error: '❌ Feil under sending. Prøv igjen.' },
    'fi': { msg_added_cart: '✓ Lisätty ostoskoriin', msg_clear_cart_q: 'Tyhjennä ostoskori?', msg_clear_yes: '✓ Kyllä, tyhjennä', msg_cancel: 'Peruuta', msg_items_word: 'tuotetta', msg_note_title: '📝 Huomautus', msg_table_occupied: 'ℹ️ Tämä pöytä vaikuttaa jo varatulta — jos istut siinä itse, kaikki on hyvin.', msg_offline: '📡 Ei internetyhteyttä. Yritä uudelleen, kun olet taas verkossa.', msg_table_required: '⚠️ Valitse pöytänumero ennen lähettämistä!', msg_no_beverage: '⚠️ Et ole lisännyt juomaa. Haluatko silti lähettää tilauksen?', msg_send_anyway: '✓ Kyllä, lähetä silti', msg_go_back: 'Takaisin', msg_order_sent: 'Tilaus lähetetty onnistuneesti! Tarjoilija saa sen pian.', msg_modal_ok: '✓ Selvä', msg_order_error: '❌ Virhe lähetyksessä. Yritä uudelleen.' },
    'el': { msg_added_cart: '✓ Προστέθηκε στο καλάθι', msg_clear_cart_q: 'Άδειασμα καλαθιού;', msg_clear_yes: '✓ Ναι, άδειασμα', msg_cancel: 'Ακύρωση', msg_items_word: 'είδη', msg_note_title: '📝 Σημείωση', msg_table_occupied: 'ℹ️ Αυτό το τραπέζι φαίνεται ήδη κατειλημμένο — αν κάθεστε εσείς εδώ, δεν υπάρχει πρόβλημα.', msg_offline: '📡 Δεν υπάρχει σύνδεση στο διαδίκτυο. Δοκιμάστε ξανά όταν συνδεθείτε.', msg_table_required: '⚠️ Επιλέξτε αριθμό τραπεζιού πριν την αποστολή!', msg_no_beverage: '⚠️ Δεν έχετε προσθέσει ποτό. Θέλετε να στείλετε την παραγγελία ούτως ή άλλως;', msg_send_anyway: '✓ Ναι, στείλε ούτως ή άλλως', msg_go_back: 'Επιστροφή', msg_order_sent: 'Η παραγγελία στάλθηκε με επιτυχία! Ο σερβιτόρος θα την παραλάβει σύντομα.', msg_modal_ok: '✓ Κατάλαβα', msg_order_error: '❌ Σφάλμα κατά την αποστολή. Δοκιμάστε ξανά.' },
    'cs': { msg_added_cart: '✓ Přidáno do košíku', msg_clear_cart_q: 'Vyprázdnit košík?', msg_clear_yes: '✓ Ano, vyprázdnit', msg_cancel: 'Zrušit', msg_items_word: 'položek', msg_note_title: '📝 Poznámka', msg_table_occupied: 'ℹ️ Tento stůl se zdá být již obsazený — pokud jste to vy, kdo tu sedí, není to problém.', msg_offline: '📡 Žádné internetové připojení. Zkuste to znovu, až budete online.', msg_table_required: '⚠️ Před odesláním vyberte číslo stolu!', msg_no_beverage: '⚠️ Nepřidali jste žádný nápoj. Chcete přesto odeslat objednávku?', msg_send_anyway: '✓ Ano, přesto odeslat', msg_go_back: 'Zpět', msg_order_sent: 'Objednávka byla úspěšně odeslána! Číšník ji brzy obdrží.', msg_modal_ok: '✓ Rozumím', msg_order_error: '❌ Chyba při odesílání. Zkuste to znovu.' },
    'hu': { msg_added_cart: '✓ Hozzáadva a kosárhoz', msg_clear_cart_q: 'Kiüríti a kosarat?', msg_clear_yes: '✓ Igen, ürítsd ki', msg_cancel: 'Mégse', msg_items_word: 'tétel', msg_note_title: '📝 Megjegyzés', msg_table_occupied: 'ℹ️ Úgy tűnik, ez az asztal már foglalt — ha ön ül itt, minden rendben.', msg_offline: '📡 Nincs internetkapcsolat. Próbálja újra, amint újra online lesz.', msg_table_required: '⚠️ Küldés előtt válassza ki az asztal számát!', msg_no_beverage: '⚠️ Nem adott hozzá italt. Mindenképpen elküldi a rendelést?', msg_send_anyway: '✓ Igen, mindenképpen küldd el', msg_go_back: 'Vissza', msg_order_sent: 'A rendelés sikeresen elküldve! A pincér hamarosan megkapja.', msg_modal_ok: '✓ Értem', msg_order_error: '❌ Hiba történt a küldés során. Próbálja újra.' },
    'vi': { msg_added_cart: '✓ Đã thêm vào giỏ hàng', msg_clear_cart_q: 'Xóa giỏ hàng?', msg_clear_yes: '✓ Có, xóa', msg_cancel: 'Hủy', msg_items_word: 'món', msg_note_title: '📝 Ghi chú', msg_table_occupied: 'ℹ️ Bàn này có vẻ đã có người — nếu đó là bạn đang ngồi đây thì không sao.', msg_offline: '📡 Không có kết nối internet. Vui lòng thử lại khi có mạng.', msg_table_required: '⚠️ Vui lòng chọn số bàn trước khi gửi!', msg_no_beverage: '⚠️ Bạn chưa thêm đồ uống nào. Bạn vẫn muốn gửi đơn hàng chứ?', msg_send_anyway: '✓ Có, vẫn gửi', msg_go_back: 'Quay lại', msg_order_sent: 'Đơn hàng đã được gửi thành công! Nhân viên sẽ nhận được sớm.', msg_modal_ok: '✓ Đã hiểu', msg_order_error: '❌ Lỗi khi gửi. Vui lòng thử lại.' },
    'th': { msg_added_cart: '✓ เพิ่มลงตะกร้าแล้ว', msg_clear_cart_q: 'ล้างตะกร้าหรือไม่?', msg_clear_yes: '✓ ใช่ ล้างเลย', msg_cancel: 'ยกเลิก', msg_items_word: 'รายการ', msg_note_title: '📝 หมายเหตุ', msg_table_occupied: 'ℹ️ โต๊ะนี้ดูเหมือนจะมีคนใช้อยู่แล้ว — หากเป็นคุณที่นั่งอยู่ที่นี่ก็ไม่มีปัญหา', msg_offline: '📡 ไม่มีการเชื่อมต่ออินเทอร์เน็ต กรุณาลองใหม่เมื่อกลับมาออนไลน์', msg_table_required: '⚠️ กรุณาเลือกหมายเลขโต๊ะก่อนส่ง!', msg_no_beverage: '⚠️ คุณยังไม่ได้เพิ่มเครื่องดื่ม ต้องการส่งคำสั่งซื้อต่อไปหรือไม่?', msg_send_anyway: '✓ ใช่ ส่งต่อไป', msg_go_back: 'ย้อนกลับ', msg_order_sent: 'ส่งคำสั่งซื้อสำเร็จแล้ว! พนักงานจะได้รับในไม่ช้า', msg_modal_ok: '✓ เข้าใจแล้ว', msg_order_error: '❌ เกิดข้อผิดพลาดขณะส่ง กรุณาลองใหม่' }
  };
  Object.keys(MSG_ADD).forEach(function (lang) {
    if (!window.I18N_PATCH[lang]) window.I18N_PATCH[lang] = {};
    Object.keys(MSG_ADD[lang]).forEach(function (key) {
      window.I18N_PATCH[lang][key] = MSG_ADD[lang][key];
    });
  });

  console.log('[i18n_patch_extra] Added Pescato/Gamberoni sauces for ' + sauceCount / 2 + ' languages, note field for ' + noteCount + ' languages, fixed pkg_degu_warn (Sabato Sera) for ' + warnCount + ' languages, misc labels for ' + Object.keys(MISC_ADD).length + ' languages, custom popup messages for ' + Object.keys(MSG_ADD).length + ' languages.');
})();
